"""Pontos fortes verificados, categorias não aplicáveis, componentes de arquitetura, grupos de issues e notas."""
from anchors import E

PROJECT = "FTTH Manager (ftth_tiiv)"
AUDIT_DATE = "18/09/2026"
COMMIT = "e446c49 (HEAD) + working tree com 108 arquivos modificados/novos (auditado o working tree)"

STRENGTHS = [
    dict(id="OK-01", title="Senhas com Argon2id e mitigação de timing na enumeração de usuários",
         desc="Argon2id (time=2, mem=64 MiB) e verificação contra hash sintético quando o e-mail não existe.",
         ev=[E("backend/app/core/security.py", "_hasher = PasswordHasher(", span=6),
             E("backend/app/core/security.py", "def dummy_verify_password(password: str) -> None:"),
             E("backend/app/modules/identity/service.py", "dummy_verify_password(password)")]),
    dict(id="OK-02", title="Sessões opacas de 256 bits, armazenadas como SHA-256, com expiração absoluta/por inatividade e revogação",
         desc="Token gerado com `secrets.token_urlsafe(48)`; só o hash vai ao banco; expira em 7 dias (absoluto) e 24 h (inatividade); desativar usuário revoga todas as sessões; novo token a cada login.",
         ev=[E("backend/app/core/security.py", "raw_token = secrets.token_urlsafe(48)"),
             E("backend/app/core/security.py", "return hashlib.sha256(raw_token.encode(\"utf-8\")).hexdigest()"),
             E("backend/app/modules/identity/service.py", "if now > user_session.expires_at:"),
             E("backend/app/modules/identity/service.py", "for s in user.sessions:")]),
    dict(id="OK-03", title="Cookie de sessão HttpOnly/SameSite=Lax/Secure em produção; nenhum token em localStorage",
         desc="O frontend só guarda a preferência de sidebar em `localStorage`; a sessão nunca fica acessível a JavaScript.",
         ev=[E("backend/app/core/dependencies.py", "httponly=True,", occ=1),
             E("backend/app/core/dependencies.py", "samesite=\"lax\",", occ=1),
             E("frontend/src/components/layout/app-shell.tsx", "localStorage.getItem(SIDEBAR_COLLAPSED_KEY)")]),
    dict(id="OK-04", title="RBAC aplicado no servidor em 89 dos 110 handlers via `require_permission`; papel resolvido a cada requisição",
         desc="O papel é lido do usuário no banco a cada request (mudança de papel/desativação vale imediatamente). Levantamento completo em `inventario-rotas.md`.",
         ev=[E("backend/app/core/dependencies.py", "def require_permission(permission: str) -> Callable[..., User]:"),
             E("backend/app/api/v1/users.py", "dependencies=[Depends(require_permission(\"users:write\")), Depends(validate_csrf)],", occ=1)]),
    dict(id="OK-05", title="CSRF exigido em todas as mutações reais (47 de 56 handlers mutantes; os 9 restantes são stubs ou cálculos somente-leitura) com comparação em tempo constante",
         desc="`validate_csrf` exige cabeçalho `X-CSRF-Token` igual ao cookie e usa `hmac.compare_digest`.",
         ev=[E("backend/app/core/dependencies.py", "def validate_csrf(request: Request) -> None:"),
             E("backend/app/core/security.py", "return hmac.compare_digest(token_a, token_b)")]),
    dict(id="OK-06", title="Sem SQL injection na aplicação: ORM com parâmetros vinculados (único SQL montado por f-string está no CLI de backup — SEC-10)",
         desc="Filtros `ilike` recebem o termo como parâmetro; `text()` só aparece com SQL estático.",
         ev=[E("backend/app/modules/customers/service.py", "stmt = stmt.where(Customer.code.ilike(search) | Customer.name.ilike(search))"),
             E("backend/app/modules/gis/service.py", "\"SET topology_revision = topology_revision + 1, updated_at = NOW() \"")]),
    dict(id="OK-07", title="Upload de anexos: magic bytes, nome no disco = UUID, sanitização de nome, contenção de path traversal e Content-Disposition: attachment",
         desc="Formatos limitados a JPEG/PNG/WebP/PDF; SVG/HTML/script rejeitados; nome original nunca usado no caminho físico.",
         ev=[E("backend/app/modules/attachments/service.py", "MAGIC_SIGNATURES = {"),
             E("backend/app/modules/attachments/service.py", "storage_filename = f\"{file_id.hex}{ext}\""),
             E("backend/app/modules/attachments/service.py", "if not str(file_path).startswith(str(base_dir)):"),
             E("backend/app/api/v1/attachments.py", "content_disposition_type=\"attachment\",")]),
    dict(id="OK-08", title="Importações/exportações: defusedxml (XXE), proteção contra zip bomb no KMZ e neutralização de injeção de fórmula em CSV",
         desc="KML/KMZ é parseado com `defusedxml`; KMZ limitado a 50 MB descompactados; CSV de entrada e de saída rejeita/neutraliza `=`, `+`, `-`, `@`.",
         ev=[E("backend/app/modules/imports/service.py", "import defusedxml.ElementTree as ET"),
             E("backend/app/modules/imports/service.py", "if total_uncompressed > 50 * 1024 * 1024:  # 50 MB"),
             E("backend/app/modules/imports/service.py", "if val.startswith((\"=\", \"@\", \"\\t\", \"\\r\")):"),
             E("backend/app/modules/exports/service.py", "def neutralize_csv_value(value: Any) -> str:")]),
    dict(id="OK-09", title="Editor de fusão: locks pessimistas ordenados, revisão topológica esperada e bump atômico",
         desc="`FOR UPDATE` na estrutura e nos terminais em ordem determinística (sem deadlock), validação de `expected_topology_revision` e `UPDATE … RETURNING` atômico da revisão.",
         ev=[E("backend/app/modules/connectivity/service.py", "select(Structure).where(Structure.id == struct_id).with_for_update()"),
             E("backend/app/modules/connectivity/service.py", "if payload.expected_topology_revision != current_rev:"),
             E("backend/app/modules/gis/service.py", "\"UPDATE network_topology_state \"")]),
    dict(id="OK-10", title="Fila de jobs em PostgreSQL com `SKIP LOCKED`, lease e limite de tentativas",
         desc="Claim seguro entre múltiplos workers e recuperação de crash por lease expirada (limitações em EST-07).",
         ev=[E("backend/app/modules/jobs/service.py", ".with_for_update(skip_locked=True)"),
             E("backend/app/modules/jobs/service.py", "AsyncJob.retry_count < AsyncJob.max_retries,")]),
    dict(id="OK-11", title="Integridade referencial e unicidade no banco: FKs RESTRICT, índices únicos parciais para vínculo ativo, migrações reversíveis e executadas em serviço one-shot",
         desc="Uma porta/ONU só tem 1 atendimento ativo (índice único parcial); `migrate` roda uma vez antes do backend (sem corrida entre réplicas); todas as 10 migrações têm `downgrade` com operações.",
         ev=[E("backend/app/modules/customers/models.py", "\"uq_active_port_service_link\","),
             E("compose.yaml", "command: [\"alembic\", \"upgrade\", \"head\"]"),
             E("backend/migrations/versions/0006_connectivity_engine.py", "def downgrade() -> None:")]),
    dict(id="OK-12", title="Frontend sem sinks de XSS, redirecionamento pós-login sanitizado e links externos com rel=noopener",
         desc="`grep -rnE 'dangerouslySetInnerHTML|innerHTML|setHTML|eval\\(|new Function|javascript:' frontend/src` só encontra a checagem defensiva de `sanitizeReturnUrl`; React escapa por padrão; cliente HTTP envia `X-CSRF-Token`.",
         ev=[E("frontend/src/features/auth/utils.ts", "export function sanitizeReturnUrl("),
             E("frontend/src/components/ui/copyable-coordinates.tsx", "rel=\"noopener noreferrer\"", occ=1),
             E("frontend/src/lib/api/client.ts", "headers.set(\"X-CSRF-Token\", csrfToken);")]),
    dict(id="OK-13", title="Contêineres não-root, banco em rede interna sem porta publicada e docs OpenAPI desativados em produção",
         desc="Backend roda como `ftthuser`, frontend como `nextjs`; a rede `internal` é `internal: true`; `/docs`, `/redoc` e `/openapi.json` só existem fora de produção.",
         ev=[E("backend/Dockerfile", "USER ftthuser"),
             E("frontend/Dockerfile", "USER nextjs"),
             E("compose.yaml", "internal: true"),
             E("backend/app/main.py", "docs_url=\"/docs\" if not settings.is_production else None,")]),
    dict(id="OK-14", title="Logs JSON estruturados com redação de campos sensíveis e X-Request-ID propagado",
         desc="Chaves como password/token/secret/cookie/csrf são mascaradas; o `request_id` acompanha logs, resposta e erros Problem Details; a mensagem 500 não expõe stack trace.",
         ev=[E("backend/app/core/logging.py", "SENSITIVE_KEY_PATTERN = re.compile("),
             E("backend/app/core/middleware.py", "response.headers[\"X-Request-ID\"] = request_id"),
             E("backend/app/core/errors.py", "detail=\"Ocorreu um erro interno inesperado. Contate o administrador com o request_id.\",")]),
    dict(id="OK-15", title="Dependências do backend sem vulnerabilidades conhecidas (pip-audit) e versões travadas por lockfile",
         desc="`pip-audit` em 2026-09-18: 55 dependências resolvidas, 0 vulnerabilidades (`evidencias/pip-audit-backend.json`); Dockerfile usa `uv sync --frozen`.",
         ev=[E("backend/uv.lock", "name = \"starlette\"", occ=2),
             E("backend/Dockerfile", "RUN uv sync --frozen --no-dev --no-install-project")]),
    dict(id="OK-16", title="Referências por ID no corpo/query são validadas quanto à existência e ao tipo antes de gravar",
         desc="Ex.: `create_service_link` verifica cliente, ONU (kind='onu') e porta; `create_measurement` verifica terminal e vínculo; `create_structure` verifica `site_id`.",
         ev=[E("backend/app/modules/customers/service.py", "raise NotFoundError(f\"Dispositivo {onu_uuid} não existe.\")"),
             E("backend/app/modules/measurements/service.py", "raise NotFoundError(\"Terminal óptico receptor não encontrado.\", code=\"terminal_not_found\")"),
             E("backend/app/modules/inventory/service.py", "if not session.scalar(select(Site.id).where(Site.id == site_uuid)):", occ=1)]),
    dict(id="OK-17", title="Rate limit de login e sessões persistidos no banco (funcionam com várias réplicas)",
         desc="Contagem de tentativas por janela em `login_attempts`; sem estado em memória do processo (limitações de política em SEC-06).",
         ev=[E("backend/app/modules/identity/service.py", "select(func.count(LoginAttempt.id)).where("),
             E("backend/app/modules/identity/models.py", "class LoginAttempt(Base):")]),
    dict(id="OK-18", title="Proteção do último administrador e If-Match obrigatório (428) na gestão de usuários",
         desc="Impede desativar/rebaixar o único admin ativo; `PATCH/DELETE /users/{id}` exigem `If-Match`.",
         ev=[E("backend/app/modules/identity/service.py", "code=\"last_admin_protection\","),
             E("backend/app/api/v1/users.py", "if if_match is None or not if_match.strip():", occ=1)]),
    dict(id="OK-19", title="Performance do frontend: busca com debounce, mapa carregado sob demanda e cache de consultas",
         desc="`data-table-filter-bar` usa debounce de 350 ms; o mapa (MapLibre) é `dynamic()`; o mapa consulta por bbox com debounce e cancelamento; TanStack Query com `staleTime`.",
         ev=[E("frontend/src/components/ui/data-table/data-table-filter-bar.tsx", "debounceMs = 350,"),
             E("frontend/src/features/map/components/map-view.tsx", "const OperationalMap = dynamic("),
             E("frontend/src/app/providers.tsx", "staleTime: 60 * 1000 * 2, // 2 minutos de cache padrão")]),
    dict(id="OK-20", title="Verificação negativa: histórico git e bundle sem segredos",
         desc="8 commits varridos (`git log --all -p`): nenhum arquivo `.env/.pem/.key` rastreado e nenhum padrão AKIA/ghp_/xox*/sk-/PRIVATE KEY; só valores de teste. O bundle `.next` local não contém os defaults de segredo. Os defaults em código/compose estão em SEC-05.",
         ev=[], cmd="git log --all --name-only --pretty=format: | sort -u | grep -Ei '(\\.env|\\.pem|\\.key|id_rsa|credentials)$'  # → vazio"),
    dict(id="OK-21", title="Suíte de testes ampla e CI executando testes, tipos, lint e restore drill",
         desc="142 funções de teste no backend, 19 arquivos de teste no frontend; o CI roda tudo e o restore drill (lacuna: nenhum teste verifica autorização por rota — EST-02/SEC-03).",
         ev=[E(".github/workflows/ci.yml", "run: uv run python scripts/restore_drill.py")]),
]

NOT_APPLICABLE = [
    ("Isolamento multi-tenant (RLS, `tenant_id`, filtro por organização)", "Instância de organização única: nenhuma tabela possui coluna de tenant/dono (`grep -riE 'tenant|org_id|owner_id|created_by' backend/app` → 0). Todas as tabelas (users, sites, structures, devices, ports, cables, cable_segments, fibers, terminals, connections, customers, service_links, attachments, audit_events, async_jobs…) são globais por design. O controle é RBAC (SEC-03/SEC-04). IDOR 'horizontal' (acesso ao objeto de outro dono) não se aplica; avaliou-se IDOR vertical (permissão por objeto)."),
    ("JWT (algoritmo, audience, expiração)", "Não há JWT: sessões opacas persistidas no banco (OK-02)."),
    ("E-mail, templates e HTML de e-mail (injeção)", "Nenhum envio de e-mail nem template server-side (`grep -riE 'smtp|jinja|Template\\(' backend/app` → 0)."),
    ("SSRF em URLs fornecidas pelo usuário", "O backend não faz requisições HTTP de saída (`httpx` está declarado em pyproject mas nenhum módulo de `app/` o usa). Tiles do mapa são buscados pelo navegador (CSP limita os hosts)."),
    ("Webhooks e pagamentos (idempotência)", "Inexistentes. A idempotência de jobs de importação foi avaliada em EST-06."),
    ("Reset de senha por link/OTP e MFA", "Inexistentes por design (ADR-0003: sem cadastro público; recuperação via CLI `bootstrap_admin --reset-password`, avaliada em SEC-08)."),
    ("Cache de servidor (stampede, chave sem tenant, TTL)", "Não há Redis/memcached nem cache de resposta; `lru_cache` só em `get_settings`. O cache existe no cliente (TanStack Query, OK-19). Ausência de cache no dashboard é tratada em PERF-01."),
    ("Goroutines, pool de conexões Go, event loop Node, lazy loading Hibernate", "Stack Python/FastAPI/SQLAlchemy síncrono: equivalentes avaliados — código síncrono em `async def` (PERF-04/05), pool/threadpool (PERF-12), N+1 do ORM (PERF-01/02/10)."),
    ("GraphQL / resolvers sem dataloader", "API REST."),
    ("Cron duplicado entre réplicas", "Não há cron externo; a limpeza periódica roda no loop do worker e é idempotente. O risco real é o oposto (worker não inicia — EST-01)."),
    ("Migrações no startup com múltiplas réplicas", "Migrações rodam num serviço one-shot `migrate` (OK-11), não no startup do backend."),
    ("Rotação de logs", "Logs em stdout/stderr; rotação delegada ao runtime do contêiner."),
    ("Sticky sessions", "Sessões em banco; não há afinidade necessária (OK-17)."),
]

# Arquitetura: componentes e dependências (singleton = ponto único)
COMPONENTS = [
    dict(id="browser", label="Navegador\n(Next.js CSR)", kind="client", singleton=False),
    dict(id="caddy", label="Caddy :80\n(proxy, CSP)", kind="edge", singleton=True),
    dict(id="frontend", label="Frontend Next.js\n(standalone :3000)", kind="app", singleton=True),
    dict(id="backend", label="Backend FastAPI\n(1 processo uvicorn)", kind="app", singleton=True),
    dict(id="worker", label="Worker de jobs\n(run_worker.py)", kind="app", singleton=True),
    dict(id="db", label="PostgreSQL 16 + PostGIS\n(único, sem réplica)", kind="data", singleton=True),
    dict(id="storage", label="Volume backend_storage\n(anexos/imports/exports)", kind="data", singleton=True),
    dict(id="tiles", label="Tiles OSM / CARTO\n(externo, via navegador)", kind="ext", singleton=False),
    dict(id="migrate", label="migrate (one-shot)\nalembic upgrade head → DB", kind="job", singleton=False),
]
# (origem, destino, rótulo)
EDGES = [
    ("browser", "caddy", "HTTP"), ("caddy", "frontend", "/*"), ("caddy", "backend", "/api/*, /health/*"),
    ("backend", "db", "SQLAlchemy pool 10+20"), ("worker", "db", "claim SKIP LOCKED"),
    ("backend", "storage", "anexos"), ("worker", "storage", "imports/exports"),
    ("browser", "tiles", "HTTPS"), ("migrate", "db", "DDL"),
]
# hotspots: componente -> ids de achados
HOTSPOTS = {
    "caddy": ["SEC-11", "EST-11"],
    "backend": ["SEC-01", "SEC-03", "PERF-01", "PERF-04", "PERF-12", "EST-13", "EST-14"],
    "worker": ["EST-01", "EST-07", "EST-05"],
    "db": ["PERF-03", "PERF-06", "EST-19"],
    "storage": ["EST-08", "EST-09", "SEC-13"],
    "frontend": ["EST-15", "SEC-15"],
}

METHOD_NOTE = [
    ("Stack detectada", "Python 3.12 · FastAPI 0.141 (Starlette 1.6) · SQLAlchemy 2 síncrono + psycopg3 + GeoAlchemy2/Shapely · PostgreSQL 16/PostGIS 3.4 · Alembic · Argon2id · Pillow · "
                        "Next.js 15.5 (React 19, TanStack Query/Table, MapLibre GL 5) · Docker Compose (db, migrate, backend, worker, frontend, Caddy 2.8) · CI GitHub Actions."),
    ("Autenticação / autorização", "Sessão opaca (cookie `ftth_session` ou Bearer) → `get_current_user` → `require_permission(perm)` (matriz por papel). CSRF por double-submit + Origin. Sem JWT."),
    ("Isolamento de tenant", "Inexistente por design (organização única): categorias 'banco sem tranca' e 'IDOR' foram mapeadas para (a) rotas sem autenticação/permissão (SEC-01/02/03/04, EST-02) e (b) IDOR vertical — permissão por tipo de objeto (anexos, clientes, jobs, exportações)."),
    ("Mapeamento das categorias", "Chaves expostas → código, compose, .env.example, CI, scripts, docs, histórico git (8 commits) e bundle `.next`. XSS → sinks React/DOM e HTML/e-mail no backend (N/A). Fundamentos → sessão/CSRF/CORS/headers/upload/SQLi/logs. "
                                 "Performance → N+1 do ORM, índices das migrações × WHERE/ORDER, código síncrono em `async def` (equivalente a event loop bloqueado), pool/threadpool, memória, escala horizontal."),
    ("Método de verificação", "Leitura integral do núcleo de segurança e dos módulos de risco; introspecção do `app` para o inventário (110 handlers); `pip-audit` e `pnpm audit`; varredura do histórico git; medições em PostgreSQL/PostGIS descartável (127.0.0.1:55432, contêiner `--rm`) com dataset sintético do próprio repositório (10.001 estruturas, 103.200 fibras)."),
    ("O que foi executado", "Somente leitura no projeto. Nenhum exploit, nenhuma requisição a ambientes reais. Único código do projeto importado: `app.main` (introspecção), serviços e schemas em ambiente descartável. Venv em `/tmp/audit-env`; `PYTHONDONTWRITEBYTECODE=1`."),
]

# Grupos de issues: (título, [labels], [ids])
ISSUE_GROUPS = [
    ("[Segurança] Exigir autenticação em /search e /dashboard/summary (e fechar a cadeia de DoS anônimo)", ["security", "severity:alta"], ["SEC-01", "SEC-16"]),
    ("[Segurança] /metrics com token padrão público e variável do compose ignorada", ["security", "severity:média"], ["SEC-02"]),
    ("[Segurança] Viewer e technician acessam PII de clientes: aplicar customers:*, anexos e auditoria por entidade", ["security", "severity:alta"], ["SEC-03", "SEC-04"]),
    ("[Segurança] Segredos default públicos e configurações mortas: validar em startup, sem defaults no compose", ["security", "severity:média"], ["SEC-05", "EST-17"]),
    ("[Segurança] Endurecer login e sessões: lockout de conta, enumeração, revogação na troca de senha, X-Forwarded-For", ["security", "severity:média"], ["SEC-06", "SEC-07", "SEC-08", "SEC-18"]),
    ("[Segurança] Validação de Origin do CSRF por startswith e token não vinculado à sessão", ["security", "severity:baixa"], ["SEC-09"]),
    ("[Segurança] Restauração de backup: extractall sem filtro e SQL a partir de nomes do arquivo; backup consistente e cifrado", ["security", "severity:média"], ["SEC-10", "EST-19"]),
    ("[Segurança] CSP com unsafe-inline/eval, sem TLS/HSTS no proxy e documentação divergente", ["security", "severity:média"], ["SEC-11"]),
    ("[Segurança] seed_demo cria admin com credencial pública sem guarda de ambiente", ["security", "severity:baixa"], ["SEC-12"]),
    ("[Segurança] Exportações de PII sem auditoria/retenção e vazamento de error_message em /jobs", ["security", "severity:média"], ["SEC-13", "SEC-14"]),
    ("[Segurança] Supply chain: advisories no frontend e CI sem scanners/gates", ["security", "severity:média"], ["SEC-15", "EST-16"]),
    ("[Arquitetura] Cobertura de auditoria: eventos de identidade, inventário, óptico e exportações", ["architecture", "severity:média"], ["EST-10", "SEC-17"]),
    ("[Arquitetura] O worker de jobs não inicia (ImportError) — importar/exportar está indisponível", ["architecture", "severity:alta"], ["EST-01", "EST-18"]),
    ("[Arquitetura] Importação: geometria de cabos descartada, lease sem heartbeat, storage fora do STORAGE_PATH e idempotência", ["architecture", "severity:alta"], ["EST-05", "EST-06", "EST-07", "EST-08"]),
    ("[Arquitetura] Autorização por padrão: rotas stub 501 sem auth e teste que varre todas as rotas", ["architecture", "severity:média"], ["EST-02", "EST-20"]),
    ("[Arquitetura] Concorrência: If-Match atômico e divisão de segmento com lock/revisão", ["architecture", "severity:média"], ["EST-03", "EST-04", "EST-21"]),
    ("[Arquitetura] Uploads: consistência disco×banco e reconciliador seguro", ["architecture", "severity:média"], ["EST-09"]),
    ("[Arquitetura] Tetos de entrada e rate limit: fiber_count ilimitado, corpo sem limite, endpoints caros", ["architecture", "severity:alta"], ["EST-11"]),
    ("[Arquitetura] UUID inválido retorna 500 e campos sem max_length", ["architecture", "severity:baixa"], ["EST-12"]),
    ("[Arquitetura] Métricas em memória: cardinalidade ilimitada de paths 404 e visão por processo", ["architecture", "severity:média"], ["EST-13"]),
    ("[Arquitetura] SPOF e estado local: preparar escala horizontal (workers, storage, backup, HA)", ["architecture", "severity:média"], ["EST-14"]),
    ("[Arquitetura] Build do frontend quebrado: COPY de /app/public inexistente", ["architecture", "severity:alta"], ["EST-15"]),
    ("[Performance] Dashboard com N+1 (2.514 queries) — agregar em SQL e cachear", ["performance", "severity:alta"], ["PERF-01"]),
    ("[Performance] Análise de impacto e rastreio óptico: N+1 por cliente/salto", ["performance", "severity:alta"], ["PERF-02", "PERF-14"]),
    ("[Performance] Upload de imagem: loop bloqueado, amplificação de memória e DecompressionBomb", ["performance", "severity:alta"], ["PERF-04"]),
    ("[Performance] Índices ausentes: terminals(entity_type, entity_id), trigram para ILIKE e created_at", ["performance", "severity:média"], ["PERF-03", "PERF-06", "PERF-07"]),
    ("[Performance] Importação/exportação em memória e por entidade (parse síncrono, N+1 de cancelamento)", ["performance", "severity:média"], ["PERF-05", "PERF-08"]),
    ("[Performance] Pool, workers e timeouts: statement_timeout, readiness, auth path e hotspot de revisão", ["performance", "severity:média"], ["PERF-12", "PERF-13", "PERF-10", "PERF-09"]),
    ("[Performance] Política de retenção para login_attempts, sessões e exportações", ["performance", "severity:baixa"], ["PERF-11"]),
]

WAVES = {
    1: ("Onda 1 — imediato (dias)", "Fechar acessos indevidos e quebras de deploy/operação de baixo esforço."),
    2: ("Onda 2 — curto prazo (2–4 semanas)", "Autorização por padrão, integridade de dados, limites e observabilidade mínima."),
    3: ("Onda 3 — médio prazo (1–3 meses)", "Cobertura de auditoria, escala horizontal, backup e otimizações estruturais."),
    4: ("Backlog", "Melhorias de baixo risco/retorno."),
}
