"""Achados de SEGURANÇA (SEC-nn). Fonte de autoria; `build_findings.py` resolve as âncoras e gera findings.json."""
from anchors import E

FINDINGS = [
    dict(
        id="SEC-01", sev="alta", sub="Autenticação / banco sem tranca",
        title="Busca global e resumo do painel acessíveis sem autenticação",
        cond="Sempre (nenhuma feature flag). `GET /api/v1/search` e `GET /api/v1/dashboard/summary` respondem 200 a qualquer cliente de rede que alcance a API; o Caddy publica `/api/*` (Caddyfile:19-21).",
        desc="`dashboard/summary` não declara nenhuma dependência de autenticação e `search` usa `get_optional_current_user` (anônimo permitido). "
             "Anônimos recebem sites, estruturas, cabos e dispositivos (inclui `serial_number`) por `ILIKE '%q%'`, além de contadores agregados (clientes, vínculos ativos, faixas de ocupação de CTOs). "
             "Só a camada `customers` da busca é protegida (`customers:read`). O teste `test_reports_dashboard_search.py:308` **codifica** o acesso anônimo como esperado, e os docs (`docs/api-catalog.md`, ADR-0003) não o declaram como decisão de produto.",
        why="Reconhecimento gratuito do inventário físico do provedor (localização de POPs, códigos de CTO/CEO, seriais de OLT/ONU) e enumeração por prefixo. Como o mesmo endpoint é caro (PERF-01), também é amplificador de DoS sem credencial (cadeia SEC-16).",
        impact="Vazamento de dados operacionais de infraestrutura crítica a qualquer host que alcance o proxy; base para engenharia social e ataques físicos/lógicos direcionados.",
        fix="Exigir `Depends(require_permission(\"reports:read\"))` (dashboard) e `map:read`/`network:read` (busca); remover `get_optional_current_user` de `/search` e decidir por permissão granular quais grupos retornar. Ajustar o teste que hoje afirma o comportamento anônimo.",
        validate="`curl -s -o /dev/null -w '%{http_code}' http://HOST/api/v1/dashboard/summary` e `.../search?q=OLT` sem cookie: deve retornar 401. Com viewer: 200.",
        accept=["Requisição sem sessão a `/api/v1/dashboard/summary` e `/api/v1/search` retorna 401 (`authentication_required`).",
                "Teste automatizado parametrizado sobre TODAS as rotas de `app` falha se algum handler fora de uma allowlist explícita (health/auth) não depender de `get_current_user` (falha hoje: 9+2 rotas; passa depois).",
                "`test_reports_dashboard_search.py` atualizado: anônimo → 401."],
        ev=[E("backend/app/api/v1/reports.py", "def get_dashboard_summary(db: Session = Depends(get_db)) -> DashboardSummaryResponse:"),
            E("backend/app/api/v1/reports.py", "current_user: User | None = Depends(get_optional_current_user),"),
            E("backend/app/modules/reports/service.py", "Device.serial_number.ilike(f\"%{clean_q}%\"),"),
            E("backend/tests/integration/test_reports_dashboard_search.py", "resp_anon = client.get(\"/api/v1/search?q=ALPHA\")"),
            E("Caddyfile", "handle /api/* {")],
        proof="medido: `docs/security-audit/tools/measure.py` (Postgres descartável, 10.001 estruturas): `GET /api/v1/dashboard/summary` sem auth → HTTP 200 (3/3 execuções); `GET /api/v1/search?q=OLT` sem auth → HTTP 200, grupos retornados: ['device'].",
        effort=1, gain=3, wave=1),

    dict(
        id="SEC-02", sev="média", sub="Chaves expostas / config",
        title="/metrics protegido por token padrão público e a variável do compose é ignorada",
        cond="Deploy via `compose.yaml` (padrão) ou qualquer deploy que não defina `METRICS_SECRET_TOKEN`. O Caddy encaminha `/api/*` (inclui `/api/v1/metrics`) para o backend.",
        desc="`config.py` define um default fixo para `METRICS_SECRET_TOKEN` (`dev-…`, mascarado). O `compose.yaml` injeta `METRICS_TOKEN` (nome diferente), que `Settings` ignora (`extra=\"ignore\"`), "
             "de modo que o default permanece ativo mesmo com `ENVIRONMENT=production`. A comparação usa `==` (não é tempo constante) e não há validação de startup que rejeite o default.",
        why="Quem conhece o default (está no repositório) faz `GET /api/v1/metrics` com `X-Metrics-Token` e obtém rotas, contagem/latência por rota, erros 5xx, estatísticas do pool de conexões e revisão topológica.",
        impact="Divulgação de informações operacionais e do mapa de rotas; facilita reconhecimento e calibração de ataques de DoS.",
        fix="Renomear no compose para `METRICS_SECRET_TOKEN` (ou aceitar `METRICS_TOKEN` via `validation_alias`); sem default (obrigatório quando `METRICS_ENABLED`); comparar com `hmac.compare_digest`; não expor `/metrics` no Caddy (rede interna/porta separada).",
        validate="Subir stack com `METRICS_TOKEN=abc…` e chamar `/api/v1/metrics` com o token default do código: deve retornar 401/403.",
        accept=["Com `ENVIRONMENT=production` e sem `METRICS_SECRET_TOKEN`, a aplicação recusa iniciar.",
                "Teste automatizado: `Settings(METRICS_TOKEN='x')` (nome do compose) ↔ token efetivo == 'x' (falha hoje; passa depois).",
                "Requisição com o default → 401/403."],
        ev=[E("backend/app/core/config.py", "METRICS_SECRET_TOKEN: str =", note="valor mascarado"),
            E("compose.yaml", "METRICS_TOKEN: ${METRICS_TOKEN:-}"),
            E("backend/app/api/v1/metrics.py", "if x_metrics_token and x_metrics_token == settings.METRICS_SECRET_TOKEN:"),
            E("Caddyfile", "handle /api/* {")],
        proof="medido: `tools/measure3.py` — com `METRICS_TOKEN` definido no ambiente, `Settings().METRICS_SECRET_TOKEN` continua igual ao default do código (True); `tools/measure2.py` — `GET /api/v1/metrics` com o default → HTTP 200.",
        effort=1, gain=2, wave=1),

    dict(
        id="SEC-03", sev="alta", sub="Permissão / dados pessoais",
        title="Papel viewer lê dados pessoais de clientes: permissão `customers:*` nunca é exigida",
        cond="Qualquer conta autenticada (inclusive `viewer`, o papel mínimo). Sem feature flag.",
        desc="A matriz de permissões atribui `customers:read/write` apenas a engineer/admin, e a busca global usa `customers:read` para decidir se mostra clientes. "
             "Porém todas as rotas `/customers` e `/service-links` exigem apenas `network:read` (leitura) ou `network:write` (escrita); `customers:*` não é exigido por nenhuma rota. "
             "`CustomerRead` devolve nome, telefone, e-mail, endereço e notas.",
        why="Um viewer (ou uma sessão de viewer roubada) exporta a base de assinantes paginando `GET /customers?page_size=200`.",
        impact="Violação de LGPD (dados pessoais a papel sem necessidade) e contradição entre política declarada (`/search`) e política aplicada (`/customers`).",
        fix="Trocar `network:read/write` por `customers:read/write` em todas as rotas de clientes e vínculos; adicionar teste de matriz papel×rota.",
        validate="Login como viewer e `GET /api/v1/customers`: deve retornar 403 `insufficient_permissions`.",
        accept=["viewer e technician recebem 403 em `GET /customers`, `GET /customers/{id}`, `GET /service-links`.",
                "Teste automatizado de matriz: para cada permissão declarada, ao menos uma rota a exige; e viewer → 403 nas rotas de clientes (falha hoje; passa depois)."],
        ev=[E("backend/app/api/v1/customers.py", "summary=\"Listar clientes\",", span=2),
            E("backend/app/core/permissions.py", "\"customers:read\",", occ=1),
            E("backend/app/modules/reports/service.py", "user_can_read_customers = has_permission(role_enum, \"customers:read\")"),
            E("backend/app/schemas/customers.py", "class CustomerRead(BaseModel):")],
        proof="medido: `tools/measure2.py` — sessão de viewer: `GET /api/v1/customers` → HTTP 200 com campos id, code, name, phone, email, address, notes.",
        effort=1, gain=3, wave=1),

    dict(
        id="SEC-04", sev="média", sub="Permissão / IDOR vertical",
        title="Anexos e trilha de auditoria ignoram a permissão da entidade dona (PII via technician)",
        cond="Papel technician (possui `attachments:read` e `audit:read`, mas não `customers:read`).",
        desc="Anexos podem ser vinculados a `customer` e `service_link`; `GET /attachments`, `/{id}` e `/{id}/download` só exigem `attachments:read`, sem consultar a permissão da entidade referenciada. "
             "`GET /audit-events` (`audit:read`) devolve `changes` — para `customer:updated` o JSON traz phone, email e address em claro.",
        why="Um technician lê documentos anexados a clientes (contratos/fotos) e o histórico de alterações com PII, contornando o bloqueio a `customers:read`.",
        impact="Segundo e terceiro caminhos para o mesmo dado pessoal de SEC-03; quebra o modelo de menor privilégio.",
        fix="Autorizar por entidade: filtrar `entity_type in ('customer','service_link')` quando o papel não tem `customers:read`; mascarar PII em `changes` ou restringir `audit:read`.",
        validate="Como technician: `GET /api/v1/attachments?entity_type=customer` e `GET /api/v1/audit-events?entity_type=customer` devem retornar 403 ou lista vazia.",
        accept=["technician não lista/baixa anexos de `customer`/`service_link`.",
                "`GET /audit-events` para technician não retorna `phone/email/address` (teste de contrato falha hoje, passa depois)."],
        ev=[E("backend/app/api/v1/attachments.py", "summary=\"Listar anexos com paginação e filtros\",", span=4),
            E("backend/app/core/permissions.py", "\"attachments:read\",", occ=1),
            E("backend/app/modules/attachments/service.py", "\"customer\": Customer,"),
            E("backend/app/api/v1/reports.py", "dependencies=[Depends(require_permission(\"audit:read\"))],"),
            E("backend/app/modules/customers/service.py", "changes[\"phone\"] = customer.phone")],
        proof="verificado por leitura, não medido (medido apenas que viewer recebe 403 em /attachments e /audit-events; technician não foi exercitado). Como medir: criar technician, anexo em customer e chamar as duas rotas.",
        effort=2, gain=2, wave=2),

    dict(
        id="SEC-05", sev="média", sub="Chaves expostas / defaults",
        title="Defaults de segredo públicos no código, no compose e no .env.example, sem validação de startup",
        cond="Deploy sem sobrescrever variáveis. O compose define `ENVIRONMENT` default `production`, mas `Settings` aceita os defaults mesmo assim.",
        desc="`SECRET_KEY`, `CSRF_SECRET` e `METRICS_SECRET_TOKEN` têm default em `config.py`; `compose.yaml` repete `${SECRET_KEY:-…}`, `${CSRF_SECRET:-…}` e `${POSTGRES_PASSWORD:-ftth…}` (senha padrão do banco). "
             "Não existe `model_validator` que rejeite defaults quando `is_production`. (`SECRET_KEY` e `CSRF_SECRET` hoje não são lidos por nenhum código — ver EST-17 — mas a senha do banco e o token de métricas são.)",
        why="Um operador que suba `docker compose up` sem `.env` obtém um sistema 'em produção' com credenciais conhecidas do repositório; quem alcançar a rede interna do Docker entra no PostgreSQL com o usuário `ftth_user`.",
        impact="Comprometimento total do banco em ambientes mal configurados; falsa sensação de segurança (a aplicação inicia normalmente).",
        fix="Remover defaults do compose para segredos (`${VAR:?defina VAR}`); `model_validator` em `Settings` que falha em `ENVIRONMENT=production` se `SECRET_KEY`/`CSRF_SECRET`/`METRICS_SECRET_TOKEN`/senha do banco forem os defaults conhecidos ou curtos.",
        validate="`ENVIRONMENT=production python -c 'from app.core.config import Settings; Settings()'` deve levantar erro.",
        accept=["Aplicação recusa iniciar em produção com qualquer default conhecido (teste unitário em `test_config.py`, falha hoje).",
                "`docker compose config` falha se `POSTGRES_PASSWORD` não estiver definido."],
        ev=[E("backend/app/core/config.py", "SECRET_KEY: str = Field(", span=4, note="valor mascarado"),
            E("backend/app/core/config.py", "CSRF_SECRET: str =", note="valor mascarado"),
            E("compose.yaml", "POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-", note="valor mascarado"),
            E("compose.yaml", "SECRET_KEY: ${SECRET_KEY:-", occ=1, note="valor mascarado"),
            E("backend/app/core/config.py", "@field_validator(\"ENVIRONMENT\", mode=\"before\")"),
            E(".env.example", "SECRET_KEY=", note="valor mascarado")],
        proof="medido: `tools/measure3.py` — `ENVIRONMENT=production` → `Settings()` instancia com `SECRET_KEY` = default (prefixo `dev-…`), `is_production=True`.",
        effort=1, gain=2, wave=1),

    dict(
        id="SEC-06", sev="média", sub="Abuso / autenticação",
        title="Rate limit de login permite travar qualquer conta (DoS de conta) e penaliza IP compartilhado",
        cond="Sempre. Basta conhecer o e-mail da vítima (ex.: admin).",
        desc="`check_login_rate_limit` conta tentativas falhas nos últimos 15 min por IP **ou** e-mail (`|`) e bloqueia com 429 antes de verificar a senha. Nenhum sucesso zera o contador. "
             "Atrás de NAT/CGNAT/LB (todos com o mesmo IP) 5 erros de qualquer usuário bloqueiam todos.",
        why="5 POSTs com senha errada para `admin@provedor…` bloqueiam o administrador legítimo por 15 min, repetível indefinidamente; sem CAPTCHA/backoff progressivo.",
        impact="Negação de acesso administrativo direcionada; em operação de campo atrás de CGNAT, bloqueio coletivo.",
        fix="Limitar por (IP, e-mail) combinados com backoff exponencial, sem bloquear login com senha correta de origem conhecida; limpar contador em sucesso; alertar em picos.",
        validate="Enviar 5 logins inválidos para um e-mail e depois um login válido de outro IP: hoje 429; deve autenticar.",
        accept=["Teste: 5 falhas de IP A para `u@x` não impedem login correto de `u@x` a partir do IP B.",
                "Teste: sucesso reinicia a janela."],
        ev=[E("backend/app/modules/identity/service.py", "(LoginAttempt.ip_address == ip_address) | (LoginAttempt.email == clean_email),"),
            E("backend/app/modules/identity/service.py", "if failed_attempts_count >= RATE_LIMIT_MAX_ATTEMPTS:"),
            E("backend/app/modules/identity/service.py", "record_login_attempt(session, ip_address, clean_email, success=True)")],
        proof="verificado por leitura, não medido. Como medir: script com `requests` contra instância local, 5 POST /auth/login inválidos e 1 válido.",
        effort=2, gain=2, wave=2),

    dict(
        id="SEC-07", sev="baixa", sub="Autenticação",
        title="Login revela contas existentes porém desativadas (403 antes de verificar a senha)",
        cond="Sempre; requer conhecer/adivinhar e-mails.",
        desc="`authenticate_user` retorna 403 `user_deactivated` para conta inativa **antes** de comparar a senha; contas inexistentes/ativas retornam 401 `invalid_credentials`.",
        why="Diferença observável de resposta permite enumerar ex-funcionários/contas desativadas sem conhecer senha.",
        impact="Enumeração de usuários (baixo impacto isolado; útil em phishing/spraying).",
        fix="Verificar a senha primeiro e só então informar desativação (ou responder 401 genérico).",
        validate="Desativar um usuário e comparar respostas a `login` (senha errada) vs usuário inexistente.",
        accept=["Respostas de login para inexistente, desativado e senha incorreta são indistinguíveis (status e corpo) — teste de contrato."],
        ev=[E("backend/app/modules/identity/service.py", "if not user.is_active:", occ=1, span=3)],
        proof="verificado por leitura, não medido.", effort=1, gain=1, wave=3),

    dict(
        id="SEC-08", sev="média", sub="Sessão / logout",
        title="Troca de senha (e reset via CLI) não revoga as demais sessões",
        cond="Sessão roubada/vazada antes da troca de senha; TTL absoluto 7 dias, inatividade 24 h.",
        desc="`change_user_password` só grava o novo hash. As linhas de `user_sessions` permanecem válidas. O mesmo vale para `bootstrap_admin --reset-password`.",
        why="A vítima troca a senha após suspeitar de comprometimento, mas o atacante mantém a sessão por até 7 dias (renovável enquanto houver atividade <24 h).",
        impact="Persistência do invasor após a remediação padrão; enfraquece o valor da troca de senha.",
        fix="Ao trocar/resetar senha, marcar `is_revoked=True` em todas as sessões do usuário exceto a atual; expor 'sair de todos os dispositivos'.",
        validate="Duas sessões do mesmo usuário; trocar senha na A; chamar `/auth/me` na B: hoje 200; deve ser 401.",
        accept=["Teste de integração: após `POST /auth/change-password`, a outra sessão recebe 401 (falha hoje)."],
        ev=[E("backend/app/modules/identity/service.py", "user.password_hash = hash_password(new_password)"),
            E("backend/app/cli/bootstrap_admin.py", "user.password_hash = hash_password(password)")],
        proof="verificado por leitura, não medido.", effort=1, gain=2, wave=2),

    dict(
        id="SEC-09", sev="baixa", sub="CSRF",
        title="Validação de Origin do CSRF usa startswith (bypass por sufixo) e o token CSRF não é vinculado à sessão",
        cond="Origem `http://localhost:3000.evil.example` (ou qualquer domínio que comece com uma origem permitida). Mitigado por SameSite=Lax do cookie de sessão e pela exigência do par cookie/cabeçalho.",
        desc="`validate_csrf` aceita a origem se `origin.startswith(allowed)` para qualquer item de `CORS_ORIGINS`. Além disso o CSRF é double-submit **sem assinatura** (o `CSRF_SECRET` não é usado): "
             "quem controlar um cookie no domínio (subdomínio vizinho) escolhe o par válido.",
        why="Defesa em profundidade quebrada: a checagem de Origin, que deveria bloquear origens estranhas, deixa passar hosts que apenas 'começam com' a origem permitida.",
        impact="Baixo isolado (SameSite=Lax protege o cookie de sessão), mas remove uma camada e cria falsa confiança.",
        fix="Comparar origens por igualdade exata de (esquema, host, porta); assinar o token CSRF com HMAC(`CSRF_SECRET`, session_id).",
        validate="`Origin: http://localhost:3000.evil.example` em POST /auth/login deve retornar 403 `csrf_origin_mismatch`.",
        accept=["Teste unitário: Origins `http://localhost:3000.evil.example` e `http://127.0.0.1:3000.attacker.test` → 403 (falha hoje)."],
        ev=[E("backend/app/core/dependencies.py", "or any(origin.startswith(allowed) for allowed in settings.CORS_ORIGINS)"),
            E("backend/app/core/security.py", "def generate_csrf_token() -> str:", span=3)],
        proof="medido: `tools/measure3.py` — `Origin: http://localhost:3000` → 401 (passou na checagem); `https://evil.example` → 403; `http://localhost:3000.evil.example` → **401 (passou)**; `http://127.0.0.1:3000.attacker.test` → **401 (passou)**.",
        effort=1, gain=1, wave=3),

    dict(
        id="SEC-10", sev="média", sub="Integridade / upload / SQL",
        title="Restauração de backup extrai tar sem filtro e monta SQL com nomes vindos do arquivo",
        cond="Operador restaura um arquivo de backup adulterado ou de origem não confiável (CLI `scripts/restore.py`). Os checksums estão dentro do próprio arquivo, portanto não autenticam.",
        desc="`tar.extractall(path=…)` é chamado sem `filter='data'` em três pontos (path traversal / escrita arbitrária de arquivo). No fallback binário, `f.stem` de cada `.bin` extraído é interpolado em "
             "`TRUNCATE TABLE {table_name} CASCADE` (injeção de SQL). O manifesto (`manifest.json`) e os SHA-256 vêm do mesmo tar, permitindo recalcular tudo.",
        why="Um arquivo de backup malicioso executa SQL com o usuário do banco e/ou grava fora do diretório de destino com as permissões do operador.",
        impact="Execução de SQL arbitrário (incl. `TRUNCATE` de tabelas) e sobrescrita de arquivos no host durante a restauração.",
        fix="`tar.extractall(..., filter='data')` e validação de nomes de membros; validar `table_name` contra `information_schema`/allowlist e citar com `psycopg.sql.Identifier`; assinar o manifesto (HMAC/GPG) e verificar antes de extrair.",
        validate="Criar tar com membro `../x` e `.bin` de nome `a;drop table users.bin` em ambiente descartável e chamar `restore_backup`: deve recusar.",
        accept=["Teste: tar com `../evil` → `ValueError`/`tarfile.FilterError` (falha hoje).",
                "Teste: nome de tabela fora da allowlist → recusado antes de qualquer SQL."],
        ev=[E("backend/app/core/backup_restore.py", "tar.extractall(path=tmp_dir)"),
            E("backend/app/core/backup_restore.py", "tar.extractall(path=extract_dir)"),
            E("backend/app/core/backup_restore.py", "tar.extractall(path=target_storage_path)"),
            E("backend/app/core/backup_restore.py", "cur.execute(f\"TRUNCATE TABLE {table_name} CASCADE;\")"),
            E("backend/app/core/backup_restore.py", "if calc_db_sha != manifest.database_checksum_sha256:")],
        proof="verificado por leitura, não medido (não executei restore). Como medir: PoC em banco/diretório descartáveis.",
        effort=2, gain=2, wave=2),

    dict(
        id="SEC-11", sev="média", sub="Headers / transporte",
        title="CSP com 'unsafe-inline'/'unsafe-eval', proxy só em HTTP com cookie Secure e sem HSTS; documentação afirma o contrário",
        cond="Deploy pelo `compose.yaml` + `Caddyfile` fornecidos.",
        desc="O CSP do Caddy permite `'unsafe-inline' 'unsafe-eval'` em `script-src`, o que anula a proteção contra XSS; `SECURITY.md` promete política 'estrita, bloqueando scripts inline'. "
             "O Caddy escuta só em `:80` com `auto_https off`, mas o compose publica `443:443` e o runbook diz 'terminação TLS'. O backend marca cookies `Secure` em produção — sem TLS à frente o login falha; "
             "com TLS externo não há HSTS.",
        why="Qualquer XSS futuro executa sem barreira do CSP; tráfego HTTP em claro se o operador não colocar TLS externo; declaração de controle inexistente induz a erro de auditoria.",
        impact="Redução das defesas em profundidade e risco de exposição de sessão em rede não confiável.",
        fix="Usar nonces/hashes do Next.js e remover `unsafe-*`; habilitar TLS no Caddy (ou documentar e testar o LB) e enviar `Strict-Transport-Security`; alinhar SECURITY.md/runbook.",
        validate="`curl -sI http://HOST/ | grep -i content-security-policy` e checar ausência de `unsafe-`; `curl -sI https://HOST/ | grep -i strict-transport`.",
        accept=["CSP sem `unsafe-inline`/`unsafe-eval` em `script-src`; teste E2E (Playwright) confirma que a UI funciona.",
                "Resposta HTTPS inclui HSTS; `docker compose up` sobe TLS ou documenta explicitamente o requisito."],
        ev=[E("Caddyfile", "Content-Security-Policy \"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:"),
            E("Caddyfile", "auto_https off"),
            E("SECURITY.md", "bloqueando scripts inline"),
            E("compose.yaml", "\"${HTTPS_PORT:-443}:443\""),
            E("docs/runbooks/deployment-and-maintenance.md", "terminação TLS")],
        proof="verificado por leitura, não medido.", effort=2, gain=2, wave=2),

    dict(
        id="SEC-12", sev="baixa", sub="Chaves expostas / seed",
        title="seed_demo cria administrador com credencial fixa pública, sem guarda de ambiente",
        cond="Operador executa `scripts/seed_demo.py` contra um banco de produção (o script é opt-in, mas não verifica `ENVIRONMENT`).",
        desc="O seed cria `admin@provedor…` com senha literal do repositório (mascarada: `Admi…`). Não há checagem de `is_production`/URL do banco.",
        why="Se executado por engano em produção, cria uma conta admin com senha conhecida por qualquer leitor do repositório.",
        impact="Tomada total do sistema nesse cenário.",
        fix="Abortar quando `ENVIRONMENT=production`; gerar senha aleatória e imprimi-la uma vez; exigir `--i-know-this-is-not-prod`.",
        validate="`ENVIRONMENT=production python scripts/seed_demo.py` deve sair com erro.",
        accept=["Teste unitário: `seed_demo` com `ENVIRONMENT=production` retorna código ≠ 0 sem tocar o banco (falha hoje)."],
        ev=[E("backend/scripts/seed_demo.py", "password_hash=hash_password(", note="valor mascarado"),
            E("backend/scripts/seed_demo.py", "def seed_demo_scenario(session: Session) -> dict[str, Any]:")],
        proof="verificado por leitura, não medido.", effort=1, gain=1, wave=3),

    dict(
        id="SEC-13", sev="média", sub="Dados pessoais / auditoria",
        title="Exportação de dados pessoais não é auditada, não expira e o download não revalida o papel (contradiz a UI)",
        cond="Camada `customers` exportada por admin; arquivo permanece em disco; qualquer engineer/admin com o `job_id` baixa.",
        desc="A UI afirma que a exportação de clientes é 'registrada permanentemente na trilha de auditoria', mas `create_export_request` não chama `record_audit_event`. "
             "O download exige só `exports:read` (engineer também), não confere o papel do solicitante nem a camada. Arquivos em `storage/exports` nunca são removidos: a rotina de retenção só limpa `ImportPreview`, apesar do nome.",
        why="LGPD: exfiltração em massa (nome, telefone, endereço) sem rastro, com cópia persistente em disco por prazo indefinido.",
        impact="Não-conformidade e impossibilidade de investigação forense; dados pessoais retidos além da necessidade.",
        fix="Auditar criação e download de exportações (ator, camadas, IP); checar no download que o solicitante é o dono ou admin; TTL configurável e job de limpeza dos arquivos.",
        validate="Exportar camada `customers` como admin e consultar `GET /audit-events`: hoje sem evento `export_*`.",
        accept=["Teste: criar exportação gera `AuditEvent(action='export_requested')` (falha hoje).",
                "Teste: arquivo com mais de N dias é removido pelo worker; download retorna 410."],
        ev=[E("backend/app/modules/exports/service.py", "if \"customers\" in payload.layers and (not user or user.role != \"admin\"):"),
            E("backend/app/modules/exports/service.py", "job_type = f\"export_{payload.format.value}\""),
            E("backend/app/modules/exports/service.py", "\"phone\": c.phone,"),
            E("backend/app/api/v1/imports_exports.py", "summary=\"Download do arquivo exportado\",", span=2),
            E("backend/app/modules/jobs/service.py", "expired_previews = db.scalars(select(ImportPreview).where(ImportPreview.expires_at < now)).all()"),
            E("frontend/src/features/imports_exports/components/export-wizard.tsx", "registrada permanentemente na trilha de auditoria do sistema.")],
        proof="verificado por leitura, não medido (`grep -n 'record_audit_event\\|audit' backend/app/modules/exports/service.py` → 0 linhas).",
        effort=2, gain=2, wave=2),

    dict(
        id="SEC-14", sev="baixa", sub="Informação sensível em respostas",
        title="GET /jobs/{id} expõe error_message cru (str(exception)) a qualquer usuário autenticado",
        cond="Job falha (ex.: IntegrityError na importação); qualquer papel autenticado que conheça o UUID do job.",
        desc="O worker grava `job.error_message = str(e)` e `get_job_by_id` o devolve. Exceções SQLAlchemy incluem SQL, parâmetros e caminhos de arquivo. A rota só exige `get_current_user` (viewer incluso).",
        why="Vaza detalhes internos (esquema, valores, caminhos) a papéis sem necessidade.",
        impact="Divulgação de informação que auxilia outros ataques.",
        fix="Persistir mensagem sanitizada/código de erro para o cliente e o detalhe apenas em log; exigir `imports:read`/`exports:read` conforme o tipo do job.",
        validate="Provocar colisão de código em importação e ler `GET /jobs/{id}` como viewer.",
        accept=["`error_message` retornado não contém 'SQL', 'psycopg' nem caminhos (`/app/`); viewer recebe 403."],
        ev=[E("backend/app/modules/jobs/service.py", "job.error_message = str(e)"),
            E("backend/app/modules/jobs/service.py", "error_message=job.error_message,"),
            E("backend/app/api/v1/imports_exports.py", "dependencies=[Depends(get_current_user)],")],
        proof="verificado por leitura, não medido.", effort=1, gain=1, wave=3),

    dict(
        id="SEC-15", sev="baixa", sub="Dependências",
        title="Dependências do frontend com advisories (maplibre-gl, postcss via next, vitest)",
        cond="`pnpm audit` (2026-09-18): 7 advisories — 1 crítica (maplibre-gl ≤6.4.0, sanitizador do Popup), 2 altas (postcss ≤8.5.17/8.5.11, em build via next), 4 moderadas. O código não usa `Popup`/`setHTML`, então a crítica não é alcançável hoje.",
        desc="`maplibre-gl@5.24.0` é vulnerável a bypass do sanitizador de HTML (`DOM.sanitize`), usado por `Popup.setHTML`; `grep -rnE 'Popup|setHTML|setText' frontend/src` → 0 usos. As de `postcss` vivem no toolchain do Next (build), e as de `vitest` são dev-only.",
        why="Se alguém introduzir `Popup.setHTML` com dados do inventário, o bypass viabiliza XSS; as demais exigem controle de entradas de build.",
        impact="Baixo hoje; risco latente de supply chain (o CI não bloqueia advisories — EST-16).",
        fix="Atualizar maplibre-gl para ≥6.4.1 (major), `next`/`postcss` e `vitest`; ativar Dependabot/`pnpm audit` no CI.",
        validate="`pnpm audit --prod` deve retornar 0 high/critical.",
        accept=["`pnpm audit --audit-level high` retorna 0 no CI (falha hoje)."],
        ev=[E("frontend/package.json", "\"maplibre-gl\": \"^5.1.0\","),
            E("frontend/pnpm-lock.yaml", "maplibre-gl@5.24.0:", occ=1)],
        proof="medido: `pnpm audit --json` em 2026-09-18 → `docs/security-audit/evidencias/pnpm-audit-frontend.json` (7 advisories). `pip-audit` no backend: 0 vulnerabilidades em 55 dependências resolvidas.",
        effort=2, gain=1, wave=3),

    dict(
        id="SEC-16", sev="alta", sub="Cadeia de exploração",
        title="Cadeia: painel/busca anônimos + N+1 de 2.514 queries + pool pequeno = DoS sem credencial",
        cond="Combina SEC-01 + PERF-01 + PERF-12. Basta alcançar `/api/v1/dashboard/summary` (Caddy publica `/api/*`).",
        desc="O endpoint anônimo executa 2 queries por CTO (2.514 statements com 10.001 estruturas). O backend roda 1 processo uvicorn e pool de 10+20 conexões, sem `statement_timeout` nem rate limit. "
             "Vinte requisições concorrentes levaram 16,9 s para concluir (p50=16,8 s), e o readiness (que precisa de conexão do pool) oscilou.",
        why="Um cliente não autenticado a ~1 req/s já mantém o processo saturado; readiness e healthcheck do compose passam a falhar, derrubando dependências (`frontend depends_on backend healthy`).",
        impact="Indisponibilidade da API para todos os usuários por um único atacante anônimo.",
        fix="Corrigir SEC-01 (exigir auth), PERF-01 (agregação em SQL único + cache curto), rate limit no Caddy para `/api/*`, `statement_timeout` e múltiplos workers.",
        validate="`tools/measure5.py`: 20 GETs concorrentes ao dashboard; alvo p95 < 1 s e 401 sem sessão.",
        accept=["Sem sessão → 401 imediato (custo O(1)).",
                "Com sessão, `/dashboard/summary` executa ≤ 10 queries com 10k estruturas (teste com contador de statements, falha hoje: 2.514)."],
        ev=[E("backend/app/api/v1/reports.py", "def get_dashboard_summary(db: Session = Depends(get_db)) -> DashboardSummaryResponse:"),
            E("backend/app/modules/reports/service.py", "ports = db.scalars(select(Port).where(Port.structure_id == cto.id)).all()", occ=1),
            E("backend/app/db/session.py", "pool_size=settings.DB_POOL_SIZE,"),
            E("backend/Dockerfile", "CMD [\"uvicorn\", \"app.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]")],
        proof="medido: `tools/measure5.py` — baseline `/health/ready`=151 ms, dashboard sequencial=1.095 ms; 20 concorrentes: wall=16,9 s, p50=16,8 s, max=16,9 s, todas HTTP 200; `/health/ready` durante a carga: [1126, 228, 259, 216, 260, 219] ms.",
        effort=2, gain=3, wave=1),

    dict(
        id="SEC-17", sev="média", sub="Cadeia de exploração",
        title="Cadeia: sessão não revogada + ausência de auditoria de auth/usuários = persistência invisível",
        cond="Combina SEC-08 + EST-10. Requer uma sessão comprometida.",
        desc="Mudanças de papel, criação/desativação de usuários, login, logout e troca de senha não geram `AuditEvent` (só `login_attempts`). Sem revogação na troca de senha (SEC-08), o invasor mantém a sessão e pode, "
             "com papel admin, criar contas ou elevar papéis (`PATCH /users/{id}`) sem deixar trilha na auditoria da aplicação.",
        why="Comprometer uma conta admin e criar um segundo admin não deixa evidência em `GET /audit-events`.",
        impact="Persistência furtiva e investigação forense inviável.",
        fix="Auditar todos os eventos de identidade (login ok/falha, logout, criação/edição/desativação, troca de senha, mudança de papel) e revogar sessões na troca de senha.",
        validate="Criar usuário via API e consultar `GET /audit-events?entity_type=user`.",
        accept=["Teste: `POST /users` e `PATCH /users/{id}` (role) produzem AuditEvent (falha hoje)."],
        ev=[E("backend/app/modules/identity/service.py", "user.role = payload.role.value"),
            E("backend/app/modules/identity/service.py", "def create_user_by_admin(session: Session, payload: UserCreate) -> User:"),
            E("backend/app/api/v1/reports.py", "description=\"Retorna histórico ordenado de mutações e ações de usuários no sistema.\",")],
        proof="verificado por leitura, não medido (`grep -rn record_audit_event backend/app` → apenas attachments, connectivity, customers, jobs).",
        effort=2, gain=2, wave=2),

    dict(
        id="SEC-18", sev="baixa", sub="Abuso / IP do cliente",
        title="Cabeçalho X-Forwarded-For confiável de qualquer origem (ProxyHeaders '*' + get_client_ip)",
        cond="Backend alcançável sem passar pelo Caddy (ex.: `compose.override.yaml.example` publica 127.0.0.1:8000; ou LB à frente que não sobrescreve o cabeçalho).",
        desc="`ProxyHeadersMiddleware(trusted_hosts=[\"*\"])` e `get_client_ip` usam o primeiro item de `X-Forwarded-For` sem allowlist de proxies. O valor vai para `login_attempts.ip_address` (VARCHAR(45)) e para `user_sessions`.",
        why="O invasor escolhe o 'IP' registrado/limitado; um valor > 45 caracteres provoca erro de banco (HTTP 500) no login.",
        impact="Evasão do limite por IP e poluição de trilhas de auditoria/sessão; 500 evitável.",
        fix="Confiar apenas nos IPs dos proxies reais (`forwarded_allow_ips`/`trusted_hosts`), validar IP com `ipaddress`, truncar/rejeitar valores inválidos.",
        validate="`curl -H 'X-Forwarded-For: <60 chars>' -X POST .../auth/login` direto no backend: hoje 500.",
        accept=["Teste: XFF inválido é ignorado e `request.client.host` é usado (falha hoje)."],
        ev=[E("backend/app/main.py", "app.add_middleware(ProxyHeadersMiddleware, trusted_hosts=[\"*\"])"),
            E("backend/app/core/dependencies.py", "forwarded = request.headers.get(\"x-forwarded-for\")"),
            E("backend/app/modules/identity/models.py", "ip_address: Mapped[str] = mapped_column(String(45), index=True, nullable=False)")],
        proof="verificado por leitura, não medido.", effort=1, gain=1, wave=3),
]
