"""Achados ESTRUTURAIS (EST-nn)."""
from anchors import E

FINDINGS = [
    dict(
        id="EST-01", sev="alta", sub="C. Consistência / D. Resiliência",
        title="O worker de jobs não inicia: ImportError em scripts/run_worker.py (importações e exportações nunca são processadas)",
        cond="Sempre que o serviço `worker` do compose sobe (comando `python scripts/run_worker.py`). Os testes passam porque usam `process_next_job`, não o script.",
        desc="`run_worker.py` importa `process_claimed_job` de `app.modules.jobs.service`, mas a função existente chama-se `process_next_job` (e faz o claim internamente). O processo termina com `ImportError` e o compose o reinicia em loop (`restart: unless-stopped`) sem healthcheck.",
        why="Todos os jobs (`import_commit`, `export_*`) ficam em `queued` para sempre; a UI de importação/exportação aguarda indefinidamente.",
        impact="Funcionalidades de importação e exportação totalmente indisponíveis em produção; falha silenciosa (crash-loop sem alerta).",
        fix="Alinhar a API (`process_claimed_job(db, job, worker_id)` extraída de `process_next_job`) ou ajustar o script; adicionar teste que importa `scripts.run_worker` e healthcheck do worker (heartbeat em tabela/arquivo).",
        validate="`docker compose logs worker` mostra `ImportError`; após a correção: criar export e observar `succeeded`.",
        accept=["Teste automatizado: `import scripts.run_worker` não levanta exceção (falha hoje).",
                "Teste E2E: `POST /exports` → job chega a `succeeded` com o worker real.",
                "Serviço `worker` com `healthcheck` no compose."],
        ev=[E("backend/scripts/run_worker.py", "process_claimed_job,", occ=1),
            E("backend/scripts/run_worker.py", "success = process_claimed_job(db, job, worker_id=worker_id)"),
            E("backend/app/modules/jobs/service.py", "def process_next_job(db: Session, worker_id: str = \"worker-default\") -> bool:"),
            E("compose.yaml", "command: [\"python\", \"scripts/run_worker.py\"]"),
            E("backend/tests/integration/test_imports_exports_jobs.py", "from app.modules.jobs.service import claim_next_job, process_next_job")],
        proof="medido: `python -c \"import scripts.run_worker\"` (importação, sem efeitos colaterais) → `ImportError: cannot import name 'process_claimed_job' from 'app.modules.jobs.service'`.",
        effort=1, gain=3, wave=1),

    dict(
        id="EST-02", sev="média", sub="A. Autorização como arquitetura",
        title="Rotas-stub 501 sem autenticação (allow-by-default): splitters, settings e occupancy",
        cond="Hoje respondem 501. O risco materializa-se quando a implementação for preenchida (o contrato OpenAPI já as expõe sem `security`).",
        desc="9 handlers ficam sem `Depends(get_current_user/require_permission)` e sem `validate_csrf`: 5 de `/splitters`, 2 de `/settings`, `structures/{id}/occupancy` (+ dashboard, SEC-01). "
             "Ao trocar `pending_endpoint()` pela implementação, a rota nasce pública. Além disso, o frontend já possui páginas de settings que chamam essas rotas e recebem 501.",
        why="Padrão estrutural: autorização é opt-in por decorator; não existe camada única (router-level dependency / política padrão negar).",
        impact="Novos endpoints 'esquecem' o controle por padrão (o mesmo mecanismo gerou SEC-01).",
        fix="Aplicar `dependencies=[Depends(get_current_user)]` no `APIRouter` raiz (`api_v1_router`) com allowlist explícita para login/csrf/health; teste que percorre `app.routes` e falha para rotas sem auth.",
        validate="`python docs/security-audit/tools/enum_routes.py` e listar handlers sem dependência de auth.",
        accept=["Teste automatizado (percorre `effective_route_contexts`) falha hoje com 11 rotas e passa depois.",
                "Rotas stub retornam 401 sem sessão."],
        ev=[E("backend/app/api/v1/splitters.py", "splitters_router = APIRouter(prefix=\"/splitters\", tags=[\"Splitters\"])"),
            E("backend/app/api/v1/settings.py", "settings_router = APIRouter(prefix=\"/settings\", tags=[\"Configurações da Organização\"])"),
            E("backend/app/api/v1/inventory.py", "def get_structure_occupancy(structure_id: str) -> StructureOccupancyResponse:"),
            E("backend/app/core/contracts.py", "def pending_endpoint(stage: str) -> NoReturn:"),
            E("backend/app/api/v1/router.py", "api_v1_router = APIRouter()")],
        proof="medido: `tools/enum_routes.py` — 16 handlers sem dependência de auth (7 públicos por design + 9 desta classe).",
        effort=1, gain=2, wave=2),

    dict(
        id="EST-03", sev="média", sub="C. Consistência de dados",
        title="Concorrência otimista (If-Match) é check-then-act: dois PATCH com a mesma versão passam (lost update)",
        cond="Edições concorrentes do mesmo recurso (usuário, site, estrutura, dispositivo, porta, cabo, cliente, medição, perfil óptico).",
        desc="`_validate_if_match` compara `current_version` lida em Python e só depois o handler altera e faz `version += 1`; o `UPDATE` não tem `WHERE version = :esperada` e a linha não é bloqueada (`with_for_update`). "
             "`VersionedModelMixin.version` é uma coluna comum (sem `version_id_col`).",
        why="Duas requisições simultâneas com `If-Match: 3` leem versão 3, ambas passam e a última grava sobrescrevendo a primeira sem 412.",
        impact="Perda silenciosa de edições no inventário; o contrato de 412 dá falsa garantia.",
        fix="Usar `version_id_col` do SQLAlchemy (ou `UPDATE … WHERE id=:id AND version=:v` verificando `rowcount`) e/ou `SELECT … FOR UPDATE` antes da validação.",
        validate="Teste com duas threads: dois `PATCH /sites/{id}` com o mesmo `If-Match`; hoje ambos 200.",
        accept=["Teste de concorrência: exatamente um dos dois PATCH retorna 200 e o outro 412 (falha hoje)."],
        ev=[E("backend/app/modules/inventory/service.py", "def _validate_if_match(if_match: str | None, current_version: int) -> None:"),
            E("backend/app/modules/inventory/service.py", "_validate_if_match(if_match, site.version)", occ=1),
            E("backend/app/modules/inventory/service.py", "site.version += 1"),
            E("backend/app/db/base.py", "version: Mapped[int] = mapped_column("),
            E("backend/app/modules/identity/service.py", "if user.version != expected_version:")],
        proof="verificado por leitura, não medido. Como medir: `concurrent.futures` com dois PATCH simultâneos contra Postgres descartável.",
        effort=2, gain=2, wave=2),

    dict(
        id="EST-04", sev="média", sub="C. Consistência de dados",
        title="Divisão de segmento de cabo sem lock, sem If-Match e sem revisão topológica esperada",
        cond="Dois usuários dividem o mesmo segmento ao mesmo tempo (ou duplo clique/reenvio).",
        desc="`split_cable_segment` lê o segmento sem `FOR UPDATE`, cria dois novos segmentos com todos os terminais e conexões, e ao final `db.delete(segment)`. O handler não recebe `If-Match` nem `expected_topology_revision` "
             "(ao contrário do editor de fusão, que trava a estrutura e valida a revisão). `bump_topology_revision` só ocorre no fim.",
        why="Duas transações concorrentes criam 2+2 segmentos e 2× terminais/fibras para o mesmo trecho; o segundo `DELETE` afeta 0 linhas (apenas aviso do SQLAlchemy) e ambos comitam.",
        impact="Topologia duplicada/corrompida (fibras com terminais órfãos), afetando rastreio e impacto.",
        fix="`SELECT … FOR UPDATE` no segmento (e nas fibras), exigir `If-Match`/`expected_topology_revision`, e falhar se o segmento já não existir.",
        validate="Teste com dois `POST …/split` simultâneos no mesmo segmento em Postgres descartável; hoje ambos 200.",
        accept=["Teste de concorrência: somente uma divisão tem sucesso; a outra recebe 409/412; contagem de segmentos = 2 (falha hoje)."],
        ev=[E("backend/app/modules/cables/service.py", "def split_cable_segment("),
            E("backend/app/modules/cables/service.py", "segment = get_cable_segment_by_id(db, segment_id)", occ=5),
            E("backend/app/modules/cables/service.py", "db.delete(segment)"),
            E("backend/app/api/v1/cables.py", "def split_segment(", span=6),
            E("backend/app/modules/connectivity/service.py", "select(Structure).where(Structure.id == struct_id).with_for_update()", note="contraste: o editor de fusão trava a estrutura")],
        proof="verificado por leitura, não medido (a corrida depende de duas transações reais).",
        effort=2, gain=2, wave=2),

    dict(
        id="EST-05", sev="alta", sub="C. Consistência de dados",
        title="Importação descarta a geometria dos cabos (cria Cable sem segmento) e o CSV inventa coordenadas",
        cond="Todo `import_commit` com entidades `cable` (GeoJSON/KML/CSV) após corrigir o worker (EST-01).",
        desc="`execute_import_commit` valida `coords` do cabo mas cria apenas `Cable(...)`: a geometria vive em `CableSegment.geometry` (a tabela `cables` não tem geometria) e nenhum segmento é criado. "
             "O contador `created_cables` informa sucesso. No CSV, se `coordinates` faltar, `parse_csv` injeta uma linha fictícia em São Paulo (`-46.6333,-23.5505`).",
        why="Cabos importados nascem sem trecho/fibras ligadas a estruturas; relatórios de capacidade e rastreio os tratam como cabos 'sem rota'. Coordenadas inventadas podem ser validadas como reais.",
        impact="Perda silenciosa de dados de geometria e dados fabricados no inventário; falsa sensação de importação completa.",
        fix="Criar `CableSegment` (com estruturas de origem/destino resolvidas) ou rejeitar cabos sem estruturas; nunca preencher coordenadas por default (marcar como erro de validação).",
        validate="Importar GeoJSON com um LineString e consultar `cable_segments` e o relatório de inconsistências.",
        accept=["Teste: após `import_commit` com 1 cabo, existe ≥1 `CableSegment` com a geometria do arquivo (falha hoje).",
                "Teste: CSV de cabo sem `coordinates` → `validation_status=error`."],
        ev=[E("backend/app/modules/jobs/service.py", "coords = c_it[\"coords\"]"),
            E("backend/app/modules/jobs/service.py", "cable = Cable(", span=7),
            E("backend/app/modules/cables/models.py", "class Cable(Base, VersionedModelMixin):"),
            E("backend/app/modules/cables/models.py", "geometry: Mapped[Any] = mapped_column(", note="geometria existe apenas em CableSegment"),
            E("backend/app/modules/imports/service.py", "# Linha fictícia padrão se não informado", span=2)],
        proof="verificado por leitura, não medido (o worker atual não roda — EST-01; a lógica foi lida e a ausência de `CableSegment(` em `execute_import_commit` confirmada).",
        effort=2, gain=3, wave=2),

    dict(
        id="EST-06", sev="baixa", sub="C. Idempotência",
        title="Idempotência do commit de importação: check-then-insert e chave global sem escopo",
        cond="Duplo clique/retry concorrente com a mesma `Idempotency-Key`; ou chave reutilizada em outra importação.",
        desc="O handler consulta `AsyncJob.idempotency_key` e só depois insere; a corrida cai na `UNIQUE` como `IntegrityError` não tratado (HTTP 500). A chave não é escopada por usuário/`import_id`: "
             "reutilizá-la devolve o `job_id` de **outra** importação. Sem limite de tamanho (coluna VARCHAR(255) → 500).",
        why="Retentativas legítimas geram 500; chaves iguais retornam o job alheio (vazamento de UUID e falso 'já processado').",
        impact="Falhas intermitentes e confusão de estado; baixo risco de duplicação (a UNIQUE protege).",
        fix="`INSERT … ON CONFLICT (idempotency_key) DO NOTHING RETURNING` e comparar `payload.import_id`; escopar a chave por (user_id, import_id); validar tamanho.",
        validate="Duas requisições simultâneas de commit com a mesma chave: hoje uma pode retornar 500.",
        accept=["Teste concorrente: ambas retornam o mesmo `job_id` e status 202/200 (falha hoje possível 500).",
                "Mesma chave com `import_id` diferente → 409."],
        ev=[E("backend/app/modules/imports/service.py", "existing_job = db.scalar(select(AsyncJob).where(AsyncJob.idempotency_key == idempotency_key))"),
            E("backend/app/modules/imports/models.py", "idempotency_key: Mapped[str] = mapped_column(")],
        proof="verificado por leitura, não medido.", effort=1, gain=1, wave=3),

    dict(
        id="EST-07", sev="média", sub="D. Resiliência de jobs",
        title="Lease do job nunca é renovada: `heartbeat()` é código morto e importações longas podem ser reexecutadas por outro worker",
        cond="2+ workers e job com duração > 60 s (importação de arquivos grandes: ~2 round-trips por entidade, ver PERF-05).",
        desc="`claim_next_job` cria lease de 60 s; `heartbeat()` está definido mas nunca é chamado (`grep -rn 'heartbeat(' backend` → só a definição), e `execute_import_commit` não renova a lease. "
             "Qualquer outro worker reivindica jobs `running` com `lease_expires_at < now` e incrementa `retry_count`.",
        why="O job em execução é reprocessado em paralelo; ambos brigam pelos mesmos `code` (UNIQUE) e o status final é decidido pelo último `commit` (dados podem existir com status `failed`).",
        impact="Importações duplicadas/conflitantes e estados inconsistentes sob escala horizontal; hoje mascarado por haver 1 worker.",
        fix="Renovar a lease a cada N entidades (thread de heartbeat ou chamadas dentro do loop) e verificar `lease_owner` antes de gravar o status final.",
        validate="Dois workers + importação com atraso artificial > 60 s; observar duas execuções.",
        accept=["Teste: job de 120 s simulados mantém `lease_expires_at` no futuro e é processado uma única vez (falha hoje)."],
        ev=[E("backend/app/modules/jobs/service.py", "def heartbeat(db: Session, job_id: uuid.UUID, worker_id: str, lease_seconds: int = 60) -> bool:"),
            E("backend/app/modules/jobs/service.py", "AsyncJob.lease_expires_at < now,"),
            E("backend/app/modules/jobs/service.py", "def execute_import_commit(db: Session, job: AsyncJob) -> dict[str, Any]:"),
            E("backend/scripts/run_worker.py", "job = claim_next_job(db, worker_id=worker_id, lease_seconds=60)")],
        proof="verificado por leitura, não medido.", effort=2, gain=2, wave=3),

    dict(
        id="EST-08", sev="média", sub="G. Configuração",
        title="Importações/exportações ignoram STORAGE_PATH: lêem `settings.STORAGE_DIR`, atributo que não existe",
        cond="Sempre; funciona no compose apenas porque `WORKDIR=/app` faz o caminho relativo `storage/…` coincidir com o volume `/app/storage`.",
        desc="`getattr(settings, \"STORAGE_DIR\", \"storage\")` sempre devolve o fallback relativo `storage` (a config define `STORAGE_PATH`). `result_path` e `file_storage_path` gravados no banco ficam relativos ao CWD do processo.",
        why="Mudar `STORAGE_PATH`, o `WORKDIR`, ou rodar o worker de outro diretório grava arquivos fora do volume persistente e quebra downloads/commits (`FileNotFoundError`).",
        impact="Perda de arquivos de importação/exportação em mudanças de configuração; comportamento diferente entre dev, CI e produção.",
        fix="Usar `Path(settings.STORAGE_PATH)/'imports'|'exports'` e persistir caminhos relativos ao storage root.",
        validate="`STORAGE_PATH=/data python -c` → verificar que `get_export_storage_path()` retorna `/data/exports`.",
        accept=["Teste unitário: com `STORAGE_PATH=/tmp/x`, os dois helpers retornam subpastas de `/tmp/x` (falha hoje)."],
        ev=[E("backend/app/modules/imports/service.py", "base_dir = os.path.join(getattr(settings, \"STORAGE_DIR\", \"storage\"), \"imports\")"),
            E("backend/app/modules/exports/service.py", "base_dir = os.path.join(getattr(settings, \"STORAGE_DIR\", \"storage\"), \"exports\")"),
            E("backend/app/core/config.py", "STORAGE_PATH: str = \"./storage\""),
            E("compose.yaml", "STORAGE_PATH: /app/storage", occ=2)],
        proof="verificado por leitura, não medido.", effort=1, gain=2, wave=2),

    dict(
        id="EST-09", sev="média", sub="C. Consistência de dados",
        title="Upload grava em disco antes do commit; falhas geram arquivos órfãos e o reconciliador pode apagar upload em andamento",
        cond="Exceção após a escrita (ex.: `DecompressionBombError`, falha no commit) ou `reconcile-orphans` executado durante um upload.",
        desc="`save_attachment` escreve o original (e a miniatura) antes de `db.commit()`. Qualquer exceção posterior deixa o arquivo sem registro. `reconcile_storage_orphans` remove todo arquivo não presente no snapshot lido do banco, "
             "incluindo o de um upload que ainda não commitou.",
        why="Uploads falhos acumulam lixo (até 10 MiB por tentativa — combinável com PERF-04); a reconciliação concorrente apaga o arquivo e o commit posterior aponta para um arquivo inexistente.",
        impact="Consumo de disco por tentativas maliciosas/falhas e, mais raramente, perda de anexo recém-enviado.",
        fix="Gravar em arquivo temporário e `os.replace` após o commit (ou registrar no banco primeiro e fazer GC por idade); reconciliador ignora arquivos com mtime recente.",
        validate="Enviar PNG que dispare `DecompressionBombError` (PERF-04) e listar `storage/attachments/originals`: arquivo permanece.",
        accept=["Teste: falha na geração de miniatura não deixa arquivo em `originals/` (falha hoje).",
                "Teste: reconciliador não remove arquivo com menos de N minutos."],
        ev=[E("backend/app/modules/attachments/service.py", "original_target_path.write_bytes(raw_content)"),
            E("backend/app/modules/attachments/service.py", "db.refresh(attachment)"),
            E("backend/app/modules/attachments/service.py", "if rel not in known_relative_paths:"),
            E("backend/app/modules/attachments/service.py", "except (UnidentifiedImageError, OSError, ValueError):")],
        proof="medido (parte): `tools/measure4.py` — PNG 14000×14000 (23,3 KiB) → `DecompressionBombError` não capturado em `generate_thumbnail_image`; a escrita do original ocorre antes (linha 215). Corrida com reconciliador: verificado por leitura, não medido.",
        effort=2, gain=1, wave=3),

    dict(
        id="EST-10", sev="média", sub="H. Observabilidade / auditoria",
        title="Trilha de auditoria cobre só anexos, conectividade, clientes e importação; usuários, inventário, cabos, óptico e exportações ficam de fora",
        cond="Sempre. `GET /audit-events` é apresentada como 'histórico de mutações e ações de usuários no sistema'.",
        desc="`record_audit_event` é usado apenas em `attachments`, `connectivity`, `customers` e `jobs`. Não há eventos para criar/alterar/desativar usuários e papéis, login/logout/troca de senha, CRUD de sites/estruturas/dispositivos/portas/cabos, "
             "perfis/medições ópticas, settings e exportações. Vários chamadores de anexos não propagam `request_id`.",
        why="Ações administrativas e alterações de inventário não são rastreáveis; a descrição da rota cria expectativa de cobertura total.",
        impact="Impossibilidade de responder 'quem alterou o quê' e de investigar incidentes (vide SEC-13, SEC-17).",
        fix="Centralizar em um decorador/dependência (ou event listener do SQLAlchemy) que audite toda mutação com ator, request_id e diff sanitizado; tornar a tabela append-only no banco (REVOKE UPDATE/DELETE ou trigger).",
        validate="`grep -rn record_audit_event backend/app | awk -F: '{print $1}' | sort | uniq -c`.",
        accept=["Teste parametrizado: cada rota mutante gera exatamente 1 AuditEvent (falha hoje para ≥ 30 rotas).",
                "Migração cria trigger que impede UPDATE/DELETE em `audit_events`."],
        ev=[E("backend/app/modules/audit/service.py", "def record_audit_event("),
            E("backend/app/api/v1/reports.py", "description=\"Retorna histórico ordenado de mutações e ações de usuários no sistema.\","),
            E("backend/app/modules/identity/service.py", "def update_user_by_admin("),
            E("backend/app/modules/inventory/service.py", "def create_site(session: Session, payload: SiteCreate) -> Site:")],
        proof="medido (contagem): `grep -rn record_audit_event backend/app` → attachments 3, connectivity 7, customers 7, jobs 2 (uso incl. import); zero nos demais módulos.",
        effort=3, gain=2, wave=3),

    dict(
        id="EST-11", sev="alta", sub="E. Abuso e limites",
        title="Sem tetos de tamanho e sem rate limit fora do login: `fiber_count` ilimitado derruba o processo com 1 request",
        cond="Papel engineer/admin (`network:write`) — ou sessão comprometida. Body sem limite no Caddy/uvicorn; uploads lidos por inteiro.",
        desc="`CableCreate.fiber_count` tem `ge=1` e nenhum `le`: `create_cable` instancia uma linha ORM `Fiber` por fibra numa única transação. Também: `await file.read()` lê todo o upload em memória antes de checar o limite; "
             "não há `request_body max_size` no Caddy nem limite no uvicorn; listas de entrada (`cable_segment_ids`, `cut_fiber_ids`) e campos de texto (`notes`) são ilimitados; nenhum endpoint além do login tem rate limit "
             "(inclusive os caros: trace, impact, budgets, simulations, search).",
        why="`POST /cables` com `fiber_count` de milhões consome CPU/RAM até OOM; uploads de vários GB são bufferizados na memória do processo.",
        impact="Negação de serviço por 1 requisição autenticada; sem defesa em camadas (proxy, app, banco).",
        fix="`le=` em `fiber_count`/`tube_count` (ex.: 1728/144), `max_length` em listas e textos; `request_body { max_size }` no Caddy e streaming com limite no upload; rate limit por IP/usuário nos endpoints caros.",
        validate="`tools/measure6.py`: tempo/memória por `fiber_count`; após a correção, 422 para valores acima do teto.",
        accept=["`POST /cables` com `fiber_count=1_000_000` → 422 (falha hoje).",
                "Upload > `MAX_UPLOAD_SIZE_BYTES` é rejeitado com 413 sem ler o corpo inteiro (teste com stream)."],
        ev=[E("backend/app/schemas/cables.py", "fiber_count: int = Field(..., ge=1, description=\"Quantidade total de fibras ópticas no cabo\")"),
            E("backend/app/modules/cables/service.py", "for pos in range(1, fibers_in_this_tube + 1):"),
            E("backend/app/api/v1/attachments.py", "raw_content = await file.read()"),
            E("backend/app/api/v1/imports_exports.py", "content = await file.read()"),
            E("backend/app/modules/identity/service.py", "RATE_LIMIT_MAX_ATTEMPTS = 5", note="único rate limit do sistema"),
            E("Caddyfile", "reverse_proxy backend:8000", occ=1)],
        proof="medido: `tools/measure6.py` (Postgres descartável) — `fiber_count=10.000`: 1,5 s, +50 MiB; `40.000`: 5,9 s, +125 MiB (≈ 0,15 ms e ≈ 2,5 KiB/fibra; extrapolação linear, não medida: 1 milhão ≈ 150 s e ≈ 2,5 GiB).",
        effort=2, gain=3, wave=1),

    dict(
        id="EST-12", sev="baixa", sub="F. Validação de entrada / H. Erros",
        title="UUID inválido em path/query/body resulta em HTTP 500 (ValueError não tratado) e strings sem max_length quebram no banco",
        cond="Qualquer chamada autenticada com `customer_id=abc` etc.",
        desc="Nos routers de clientes, atendimentos e conectividade, `uuid.UUID(param)` é chamado sem `try/except` (17 pontos, 14 rotas). `topology/trace` e `create_service_link` fazem o mesmo. `CustomerUpdate.phone/email/address` não têm `max_length` "
             "enquanto as colunas são VARCHAR(30/100/255) → `DataError` → 500.",
        why="Entrada malformada produz 500 (ruído em métricas e alertas, log de stack trace) em vez de 422/404; mascara falhas reais.",
        impact="Observabilidade degradada e superfície de erro 5xx controlável pelo cliente.",
        fix="Tipar parâmetros como `uuid.UUID` nos handlers (FastAPI valida e responde 422) e adicionar `max_length` alinhado às colunas.",
        validate="`GET /api/v1/customers/not-a-uuid` com sessão: hoje 500.",
        accept=["Teste: `GET /customers/not-a-uuid` → 422 (falha hoje)."],
        ev=[E("backend/app/api/v1/customers.py", "return service.get_customer_by_id(db, uuid.UUID(customer_id))"),
            E("backend/app/modules/topology/service.py", "start_uuid = uuid.UUID(request.start_terminal_id)"),
            E("backend/app/modules/customers/service.py", "customer_uuid = uuid.UUID(payload.customer_id)"),
            E("backend/app/schemas/customers.py", "phone: str | None = None", occ=1),
            E("backend/app/modules/customers/models.py", "phone: Mapped[str | None] = mapped_column(String(30), nullable=True)")],
        proof="medido: `tools/measure2.py` — `GET /api/v1/customers/not-a-uuid` (sessão viewer) → HTTP 500 (`application/problem+json`, `internal_server_error`).",
        effort=1, gain=1, wave=3),

    dict(
        id="EST-13", sev="média", sub="D. Resiliência / H. Observabilidade",
        title="Métricas em memória com cardinalidade ilimitada: paths 404 distintos crescem o dicionário sem limite (e são por-processo)",
        cond="Qualquer cliente (não requer autenticação): requisições a caminhos inexistentes.",
        desc="`RequestIDMiddleware` registra `request.url.path` quando a rota não foi resolvida (`route_format=None`); `normalize_route_path` só troca UUIDs e números por `{id}`. "
             "Cada path 404 diferente cria chaves novas em `_http_requests` e `_http_durations` que nunca são removidas. As métricas também são locais ao processo (o worker não aparece; `record_job` nunca é chamado).",
        why="Um scanner (ou atacante) fazendo `GET /a1`, `/a2`… incha a memória do processo indefinidamente e o endpoint `/metrics`.",
        impact="Vazamento de memória controlável por anônimos; métricas incompletas sob múltiplos processos/réplicas.",
        fix="Usar um rótulo fixo (`__unmatched__`) quando não houver rota; limitar o número de chaves; exportar métricas por processo com agregação (prometheus multiprocess) ou instrumentar o worker.",
        validate="`tools/measure2.py`: 300 GETs a paths 404 distintos.",
        accept=["Teste: 10.000 paths 404 distintos deixam `len(_http_requests)` constante (falha hoje)."],
        ev=[E("backend/app/core/middleware.py", "route_format = getattr(route, \"path_format\", None)", occ=1),
            E("backend/app/core/metrics.py", "clean = UUID_PATTERN.sub(\"{id}\", path)"),
            E("backend/app/core/metrics.py", "self._http_requests[req_key] = self._http_requests.get(req_key, 0) + 1"),
            E("backend/app/core/metrics.py", "def record_job(self, job_type: str, status: str) -> None:")],
        proof="medido: `tools/measure2.py` — chaves de `_http_requests`: 8 antes → 308 depois de 300 GETs a paths 404 distintos (+300).",
        effort=1, gain=2, wave=2),

    dict(
        id="EST-14", sev="média", sub="D. Resiliência / escala horizontal",
        title="SPOF e estado local: 1 processo uvicorn, 1 backend com `container_name` fixo, storage em volume local, métricas por processo",
        cond="Ao tentar escalar (2+ réplicas/hosts) ou em falha de um único container.",
        desc="`CMD uvicorn` sem `--workers`; `container_name: ftth_backend` impede `--scale`; anexos/exportações vivem em volume Docker local (`backend_storage`) compartilhado apenas no mesmo host; métricas em dicionário do processo (EST-13); "
             "PostgreSQL único sem réplica/backup automático (há `scripts/backup.sh` manual); worker sem healthcheck. Rate limit de login e sessões estão no banco (**correto**: escalam).",
        why="Queda do container/host derruba tudo; réplicas em outro host não veem os arquivos; sem redundância.",
        impact="Disponibilidade limitada a 1 nó; risco de perda de anexos por falha de disco.",
        fix="Documentar/implementar: `--workers N` ou múltiplas réplicas sem `container_name`; storage em objeto (S3/MinIO) ou NFS; backup agendado + teste de restauração; réplica de leitura/HA do banco; healthcheck do worker.",
        validate="`docker compose up --scale backend=2` → falha por `container_name`.",
        accept=["`docker compose up --scale backend=2` sobe duas réplicas saudáveis atrás do Caddy.",
                "Anexos acessíveis por qualquer réplica (teste de download após upload em outra réplica)."],
        ev=[E("backend/Dockerfile", "CMD [\"uvicorn\", \"app.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]"),
            E("compose.yaml", "container_name: ftth_backend"),
            E("compose.yaml", "- backend_storage:/app/storage", occ=1),
            E("backend/app/core/metrics.py", "self._http_requests: dict[tuple[str, str, int], int] = {}")],
        proof="verificado por leitura, não medido.", effort=3, gain=2, wave=3),

    dict(
        id="EST-15", sev="alta", sub="G. Configuração e deploy",
        title="Build do frontend falha: Dockerfile copia /app/public, diretório que não existe",
        cond="`docker compose build frontend` / `up --build` a partir do repositório.",
        desc="O estágio `runner` faz `COPY --from=builder /app/public ./public`, mas `frontend/public` não existe e não há arquivos rastreados nele (`git ls-files frontend | grep -c '^frontend/public'` → 0). O Next.js não cria `public`.",
        why="BuildKit aborta com `\"/app/public\": not found`; a stack oficial não sobe do zero.",
        impact="Bloqueio total do deploy pelo caminho oficial (imagem do frontend não é gerada).",
        fix="Criar `frontend/public/.gitkeep` ou remover a linha `COPY … /app/public` (ou torná-la condicional). Adicionar `docker build` ao CI.",
        validate="`docker build -f frontend/Dockerfile frontend` deve concluir.",
        accept=["Job de CI `docker compose build` passa (falha hoje)."],
        ev=[E("frontend/Dockerfile", "COPY --from=builder /app/public ./public")],
        proof="reproduzido em Dockerfile equivalente isolado (`tools/repro-copy-missing-dir/Dockerfile`): `ERROR … \"/app/public\": not found`. O build real do frontend não foi executado (pnpm install pesado); a ausência do diretório foi verificada no working tree e no git.",
        effort=1, gain=3, wave=1),

    dict(
        id="EST-16", sev="média", sub="G. Configuração / supply chain",
        title="CI sem varredura de dependências, segredos ou SAST, sem build de imagens e sem `permissions:` mínimas",
        cond="Todo push/PR.",
        desc="O workflow roda ruff, mypy, pytest, restore drill, eslint, tsc e vitest, mas nenhum `pip-audit`/`pnpm audit`, secret scan, CodeQL/Semgrep, `docker build` nem `trivy`. Actions são fixadas por tag (`@v4`), não por SHA, e o workflow não declara `permissions:`. "
             "Resultado: o CI ficaria verde com os 7 advisories do frontend (SEC-15) e com o Dockerfile quebrado (EST-15).",
        why="Regressões de segurança e de build chegam à branch principal sem sinal.",
        impact="Ausência de gates de qualidade de supply chain.",
        fix="Adicionar `pip-audit`, `pnpm audit --audit-level high`, gitleaks, CodeQL, `docker compose build`, trivy; `permissions: contents: read`; fixar actions por SHA.",
        validate="Executar os scanners localmente (feito neste relatório: `pip-audit` limpo; `pnpm audit` → 7).",
        accept=["Job `security` falha o CI quando existe advisory high/critical (hoje inexistente)."],
        ev=[E(".github/workflows/ci.yml", "run: uv run pytest --cov=app --cov-report=xml -v"),
            E(".github/workflows/ci.yml", "run: pnpm test"),
            E(".github/workflows/ci.yml", "uses: actions/checkout@v4", occ=1),
            E(".github/workflows/ci.yml", "concurrency:")],
        proof="verificado por leitura, não medido.", effort=2, gain=2, wave=2),

    dict(
        id="EST-17", sev="baixa", sub="G. Configuração",
        title="Configurações declaradas e nunca usadas: SECRET_KEY, CSRF_SECRET, METRICS_ENABLED, DEBUG, MAX_TRACE_HOPS",
        cond="Sempre.",
        desc="`grep` mostra que `SECRET_KEY`, `CSRF_SECRET`, `METRICS_ENABLED` e `MAX_TRACE_HOPS` não são lidos por nenhum código (apenas `DEBUG` vai a um log). O teto do rastreio óptico vem do cliente (`TraceRequest.max_hops ≤ 500`), não da config.",
        why="Operadores acreditam controlar CSRF/métricas/teto de saltos por variáveis que não têm efeito.",
        impact="Falsa sensação de segurança; parte do problema de SEC-02/SEC-05/SEC-09.",
        fix="Remover ou implementar (CSRF assinado com `CSRF_SECRET`, `/metrics` condicionado a `METRICS_ENABLED`, `min(request.max_hops, MAX_TRACE_HOPS)`).",
        validate="`grep -rn 'MAX_TRACE_HOPS\\|METRICS_ENABLED\\|CSRF_SECRET' backend/app`.",
        accept=["Nenhuma variável de `Settings` sem leitor (teste que varre `Settings.model_fields` × `grep` no código; falha hoje)."],
        ev=[E("backend/app/core/config.py", "MAX_TRACE_HOPS: int = 300"),
            E("backend/app/core/config.py", "METRICS_ENABLED: bool = True"),
            E("backend/app/schemas/topology.py", "le=500,")],
        proof="medido (grep): `grep -rn 'MAX_TRACE_HOPS\\|METRICS_ENABLED\\|CSRF_SECRET\\|SECRET_KEY' backend/app` → só `config.py`.",
        effort=1, gain=1, wave=3),

    dict(
        id="EST-18", sev="baixa", sub="H. Observabilidade",
        title="Worker sem logs JSON/correlation-id, sem healthcheck e sem métricas de jobs",
        cond="Sempre.",
        desc="`run_worker.py` usa `logging.basicConfig` com formato pseudo-JSON (quebra com aspas na mensagem), sem `request_id`/`job_id` de contexto; `metrics_collector.record_job` nunca é invocado; `worker` não tem `healthcheck` no compose; erros do job viram texto em `error_message`.",
        why="Falhas do worker (vide EST-01) passam despercebidas.",
        impact="Detecção tardia de incidentes em filas.",
        fix="Reutilizar `setup_logging`, incluir `job_id`, incrementar `record_job` e expor heartbeat/healthcheck.",
        validate="`docker compose ps` (worker sem health) e `grep -rn 'record_job(' backend`.",
        accept=["Log do worker é JSON válido por linha e contém `job_id` (teste de parsing)."],
        ev=[E("backend/scripts/run_worker.py", "format='{\"timestamp\": \"%(asctime)s\", \"level\": \"%(levelname)s\", \"logger\": \"%(name)s\", \"message\": \"%(message)s\"}',"),
            E("backend/app/core/metrics.py", "def record_job(self, job_type: str, status: str) -> None:")],
        proof="medido (grep): `grep -rn 'record_job(' backend` → só a definição.", effort=1, gain=1, wave=3),

    dict(
        id="EST-19", sev="média", sub="C. Consistência / backup",
        title="Backup por fallback psycopg não é snapshot consistente e o arquivo é gravado sem criptografia",
        cond="Ambiente sem `pg_dump` no PATH (fallback), ou operação com escritas concorrentes; backups armazenados fora do host.",
        desc="O fallback copia tabela a tabela com `COPY … TO STDOUT` numa conexão em READ COMMITTED (sem `REPEATABLE READ`/`pg_export_snapshot`), então tabelas ficam em instantes diferentes; os anexos são arquivados depois, sem congelamento. "
             "O `.tar.gz` final contém hashes de senha e PII de clientes em texto claro (sem criptografia).",
        why="Restauração pode violar FKs/invariantes (ex.: conexões sem terminais) e o backup vaza tudo se o arquivo escapar.",
        impact="Risco de backup inconsistente e de vazamento de dados de backup.",
        fix="Abrir transação `REPEATABLE READ READ ONLY`, ou exigir `pg_dump -Fc`; criptografar (age/gpg) e assinar o pacote.",
        validate="Executar backup durante carga de escrita e restaurar em base descartável; rodar checagens de FK.",
        accept=["Teste: backup com escritas concorrentes restaura sem violação de FK (hoje sem cobertura).",
                "Arquivo de backup é criptografado (teste verifica que `tar` não abre sem chave)."],
        ev=[E("backend/app/core/backup_restore.py", "with psycopg.connect(raw_url) as conn, conn.cursor() as cur:", occ=1),
            E("backend/app/core/backup_restore.py", "with open(t_file, \"wb\") as f, cur.copy(f\"COPY {t} TO STDOUT (FORMAT binary)\") as copy:"),
            E("backend/app/core/backup_restore.py", "tar.add(db_dump_file, arcname=\"database.dump\")")],
        proof="verificado por leitura, não medido.", effort=2, gain=1, wave=3),

    dict(
        id="EST-20", sev="baixa", sub="A. Autorização como arquitetura",
        title="Matriz de permissões duplicada em backend e frontend (com divergência) e gates de UI inexistentes",
        cond="Sempre.",
        desc="A matriz existe em `permissions.py` e em `rbac.ts` (cópias manuais; `telemetry:write` só no frontend). `AuthGuard`, `PermissionGate` e o campo `permission` da navegação nunca são usados: a UI mostra ações que o servidor recusará (UX) e não há fonte única.",
        why="Divergência silenciosa entre o que a UI acredita e o que o servidor impõe; sem teste que compare os dois.",
        impact="Manutenção frágil; erros de UX; risco de decisões de segurança baseadas na UI.",
        fix="Gerar `rbac.ts` a partir do backend (endpoint `/auth/me` já devolve `permissions`) e aplicar `PermissionGate` nas ações de escrita; teste de paridade.",
        validate="Comparar chaves de `ROLE_PERMISSIONS` das duas linguagens.",
        accept=["Teste de paridade backend×frontend passa; UI oculta ações sem permissão."],
        ev=[E("backend/app/core/permissions.py", "ROLE_PERMISSIONS: dict[UserRole, set[str]] = {"),
            E("frontend/src/lib/permissions/rbac.ts", "export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {"),
            E("frontend/src/lib/permissions/rbac.ts", "\"telemetry:write\",", occ=1),
            E("frontend/src/app/(app)/layout.tsx", "<AuthGuard>")],
        proof="medido (grep): `grep -rn 'PermissionGate\\|requiredPermission' frontend/src` fora de `components/auth/` → 0 usos.",
        effort=2, gain=1, wave=4),

    dict(
        id="EST-21", sev="baixa", sub="B. Camadas e acoplamento",
        title="Lógica crítica duplicada: 6 cópias da validação de If-Match e regra/consulta dentro de handlers",
        cond="Sempre; amplifica EST-03 (a correção precisa ser replicada em 6 módulos).",
        desc="`_validate_if_match` existe copiado em inventory, customers, connectivity, measurements e optical, e `_check_optimistic_lock` em cables (mensagens diferentes). "
             "Além disso o handler `download_export` consulta o banco, valida estado do job, resolve content-type e caminho de arquivo; parte da lógica de auditoria também é importada dentro do handler (`reports.py`).",
        why="Cada cópia pode divergir (já divergem nas mensagens/tratamento de aspas); corrigir a concorrência otimista exige editar 6 lugares; regra no handler dificulta testes unitários.",
        impact="Risco de correção parcial e de comportamento inconsistente entre recursos.",
        fix="Extrair `core/concurrency.py` (`assert_version(current, if_match)` + atualização atômica) e mover a lógica de download para `modules/exports/service.py`.",
        validate="`grep -rn '_validate_if_match\\|_check_optimistic_lock' backend/app`: 6 definições hoje; alvo 1.",
        accept=["Uma única implementação de verificação de versão (teste que falha se houver definição duplicada; falha hoje)."],
        ev=[E("backend/app/modules/inventory/service.py", "def _validate_if_match(if_match: str | None, current_version: int) -> None:"),
            E("backend/app/modules/customers/service.py", "def _validate_if_match(if_match: str | None, current_version: int) -> None:"),
            E("backend/app/modules/connectivity/service.py", "def _validate_if_match(if_match: str | None, current_version: int) -> None:"),
            E("backend/app/modules/measurements/service.py", "def _validate_if_match(if_match: str | None, current_version: int) -> None:"),
            E("backend/app/modules/optical/service.py", "def _validate_if_match(if_match: str | None, current_version: int) -> None:"),
            E("backend/app/modules/cables/service.py", "def _check_optimistic_lock(current_version: int, if_match: str | None) -> None:"),
            E("backend/app/api/v1/imports_exports.py", "job = db.get(AsyncJob, uid)")],
        proof="medido (grep + AST): 6 definições duplicadas. Verificação de ciclos: análise AST do grafo de imports de `backend/app` → **nenhum ciclo em nível de módulo** (há acoplamento entre pacotes gis↔inventory e 5 imports locais em `optical/service.py:220-231`, sem ciclo).",
        effort=1, gain=1, wave=4),
]
