"""Achados de PERFORMANCE / ESCALABILIDADE (PERF-nn). Cada um traz gatilho, ordem de crescimento e método de validação."""
from anchors import E

FINDINGS = [
    dict(
        id="PERF-01", sev="alta", sub="A. Banco (N+1)",
        title="Dashboard: 2 queries por CTO (N+1) — 2.514 statements e ~1 s com 10 mil estruturas, sem autenticação",
        cond="Cada requisição a `GET /api/v1/dashboard/summary`; cresce com o nº de CTOs não aposentadas.",
        desc="`calculate_dashboard_summary` carrega todas as CTOs e, dentro do `for cto in ctos`, executa `SELECT ports` e `SELECT service_links` por CTO; as contagens poderiam ser um único `GROUP BY`. O endpoint não exige autenticação (SEC-01).",
        why="Custo por request O(CTOs) em round-trips; concorrência satura o único processo e o pool de conexões (SEC-16).",
        impact="Latência ~1 s com 10 mil estruturas (medido), degradação linear e amplificação de DoS.",
        fix="Uma consulta agregada (`COUNT … GROUP BY structure_id` com `LEFT JOIN` de vínculos ativos) e cache de 15–30 s (invalidação pela `topology_revision`).",
        validate="`tools/measure.py` (contador de statements) antes/depois; alvo ≤ 10 statements e p95 < 200 ms com 10k estruturas.",
        accept=["Teste com contador de statements: `/dashboard/summary` executa ≤ 10 queries com 10.001 estruturas (falha hoje: 2.514).",
                "Benchmark `tools/measure5.py`: 20 concorrentes concluem em < 3 s (hoje 16,9 s)."],
        trigger="Dói desde ~1 s/request em 10 mil estruturas (medido); a partir de dezenas de requisições/s (dashboard abre a cada carga de UI) satura 1 worker.",
        growth="O(C) queries por request (C = nº de CTOs); 2 statements por CTO.",
        ev=[E("backend/app/modules/reports/service.py", "for cto in ctos:", occ=1),
            E("backend/app/modules/reports/service.py", "ports = db.scalars(select(Port).where(Port.structure_id == cto.id)).all()", occ=1),
            E("backend/app/modules/reports/service.py", "active_links = db.scalars(", occ=1)],
        proof="medido: `tools/measure.py` (Postgres 16/PostGIS descartável, 10.001 estruturas, 5.050 cabos, 103.200 fibras, 206.428 terminais) — `GET /api/v1/dashboard/summary`: run1=1.524 ms, run2=1.018 ms, run3=1.129 ms; **2.514 SQL statements por requisição**.",
        effort=1, gain=3, wave=1, rank=1),

    dict(
        id="PERF-02", sev="alta", sub="A. Banco (N+1) / B. Volume",
        title="Análise de impacto: carrega todos os clientes e roda um rastreio óptico completo por vínculo ativo (62 statements por vínculo)",
        cond="`POST /api/v1/topology/impact` (papel viewer basta). Cresce com nº de clientes com vínculo ativo × saltos.",
        desc="`analyze_cable_impact` faz `select(Customer)` de toda a base, e para cada vínculo ativo executa consultas de CTO/ONU/terminal e chama `trace_optical_path` (BFS com várias queries por salto). `cable_segment_ids` não tem `max_length`.",
        why="O custo total é O(clientes × saltos × queries/salto) numa única requisição síncrona de um papel de baixo privilégio, sem rate limit.",
        impact="Requisições de minutos/horas em bases reais; pool esgotado; qualquer viewer pode derrubar a API.",
        fix="Resolver o impacto em SQL/grafo em memória: carregar terminais/conexões/arestas uma vez (ou CTE recursiva) e fazer BFS único a partir dos segmentos rompidos; mover para job assíncrono para bases grandes; limitar `cable_segment_ids`.",
        validate="`tools/measure2.py` (contador de statements) e `EXPLAIN ANALYZE`; repetir com N clientes gerados.",
        accept=["Teste: statements de `/topology/impact` independem do nº de clientes (≤ 30) — falha hoje (62 por vínculo).",
                "`cable_segment_ids` limitado (`max_length`) com 422 acima do teto."],
        trigger="Custo proporcional a C (clientes ativos): medido 62 statements e ~80–104 ms para **1** vínculo; com C=1.000 ≈ 62.000 statements (extrapolação linear, não medida).",
        growth="O(C × H × q): C clientes ativos, H saltos do trajeto, q≈5 queries/salto.",
        ev=[E("backend/app/modules/topology/service.py", "all_customers = db.scalars("),
            E("backend/app/modules/topology/service.py", "for link in active_links:"),
            E("backend/app/modules/topology/service.py", "trace_res = trace_optical_path(db, trace_req)"),
            E("backend/app/schemas/topology.py", "cable_segment_ids: list[str] = Field(")],
        proof="medido: `tools/measure2.py` — viewer, 1 cliente / 1 vínculo: **62 SQL statements**, 104 ms e 80 ms (2 execuções). A partir daí, escala linear é extrapolação, rotulada como tal.",
        effort=3, gain=3, wave=2, rank=2),

    dict(
        id="PERF-03", sev="média", sub="A. Banco (índices)",
        title="Falta índice em terminals(entity_type, entity_id): buscas do rastreio e do impacto fazem Seq Scan em 206 mil linhas",
        cond="Todas as consultas `Terminal.entity_type == 'port' AND Terminal.entity_id = …` (rastreio, impacto, orçamento óptico, medições).",
        desc="A coluna `entity_id` foi adicionada na migração 0006 sem índice e o modelo declara apenas `idx_terminals_kind_structure` e `idx_terminals_occupancy`. O `EXPLAIN ANALYZE` mostra `Parallel Seq Scan on terminals`.",
        why="Cada lookup varre a tabela inteira; o impacto (PERF-02) faz vários por cliente.",
        impact="Latência linear no tamanho de `terminals`, multiplicada por N chamadas por request.",
        fix="`CREATE INDEX CONCURRENTLY idx_terminals_entity ON terminals (entity_type, entity_id);` via migração.",
        validate="`EXPLAIN (ANALYZE) SELECT * FROM terminals WHERE entity_type='port' AND entity_id=:id` antes/depois: deve usar Index Scan (< 1 ms).",
        accept=["Migração cria o índice; teste de plano (`EXPLAIN`) afirma `Index Scan` (falha hoje)."],
        trigger="Custo cresce com o nº de terminais (2 por fibra); medido 12–14 ms/lookup com 206.428 linhas.",
        growth="O(T) por lookup (T = terminais) → O(T·N) por request.",
        ev=[E("backend/app/modules/connectivity/models.py", "entity_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)"),
            E("backend/app/modules/connectivity/models.py", "Index(\"idx_terminals_occupancy\", \"occupancy\"),"),
            E("backend/migrations/versions/0006_connectivity_engine.py", "sa.Column(\"entity_id\", postgresql.UUID(as_uuid=True), nullable=True),"),
            E("backend/app/modules/topology/service.py", "Terminal.entity_id.in_(onu_ports),")],
        proof="medido: `EXPLAIN (ANALYZE)` em `tools/measure2.py` — `Parallel Seq Scan on terminals … Rows Removed by Filter: 68809 (×3 workers)`, Execution Time 12,5–14,4 ms (206.428 linhas).",
        effort=1, gain=2, wave=1, rank=5),

    dict(
        id="PERF-04", sev="alta", sub="D. Conexões e concorrência / F. Memória",
        title="Upload de anexo: handler async executa I/O e Pillow síncronos no event loop e uma PNG de 100 KiB consome +339 MiB",
        cond="`POST /api/v1/attachments` por qualquer technician/engineer/admin (ou sessão comprometida); PNG grande com poucos KiB.",
        desc="`upload_attachment` é `async def`, lê o corpo inteiro (`await file.read()`) e chama `save_attachment` sincronamente (Pillow `convert('RGB')` + `thumbnail(LANCZOS)` + `WEBP method=6`, escrita em disco e commit) — bloqueando o event loop do único processo. "
             "O limite de 10 MiB é do arquivo comprimido; o Pillow só avisa acima de 89 Mpx e levanta `DecompressionBombError` (não capturado → 500) acima de 178 Mpx.",
        why="Um upload de 100 KiB (88 Mpx) aloca centenas de MiB e ocupa o loop ~0,7 s; poucos uploads paralelos causam OOM e travam **todas** as requisições (inclusive `async def` de import).",
        impact="DoS por usuário de baixo privilégio; latência global durante uploads; 500 + arquivo órfão (EST-09).",
        fix="Declarar o handler `def` (threadpool) ou `run_in_threadpool`; validar dimensões antes de decodificar (`Image.open` → checar `size`) com teto ~25 Mpx e capturar `DecompressionBombError`; ler o corpo em streaming com limite.",
        validate="`tools/measure4.py`: RSS pico e tempo por upload; alvo < +50 MiB e rejeição 422 acima do teto.",
        accept=["PNG 9400×9400 → 422 antes de decodificar; RSS do processo não cresce > 50 MiB (teste com `tracemalloc`, falha hoje).",
                "PNG 14000×14000 → 422 (hoje 500 por exceção não tratada)."],
        trigger="1 upload de 100 KiB já causa +339 MiB (medido); 4–5 simultâneos ≈ 1,5 GiB (extrapolação linear).",
        growth="O(W×H) memória e CPU por upload, independente do tamanho do arquivo comprimido.",
        ev=[E("backend/app/api/v1/attachments.py", "async def upload_attachment("),
            E("backend/app/api/v1/attachments.py", "raw_content = await file.read()"),
            E("backend/app/modules/attachments/service.py", "thumb_img = img.convert(\"RGB\")"),
            E("backend/app/modules/attachments/service.py", "except (UnidentifiedImageError, OSError, ValueError):")],
        proof="medido: `tools/measure4.py` — PNG 9400×9400 (88,4 Mpx, **100 KiB**): passa `inspect_file_content`; `generate_thumbnail_image` = 0,67 s, RSS pico 516 MiB (antes 177 MiB) → **+339 MiB**. PNG 14000×14000 (23,3 KiB): `DecompressionBombError` não capturado.",
        effort=1, gain=3, wave=1, rank=3),

    dict(
        id="PERF-05", sev="média", sub="B. Volume / C. Caminho da requisição",
        title="Importação: parse síncrono de até 20 MB dentro de handler async, tudo em memória, e 1 SELECT de cancelamento por entidade",
        cond="`POST /imports/preview` com arquivos grandes; commit no worker.",
        desc="`preview_import` é `async def` e chama `create_import_preview` sincronamente (`json.loads` de até 20 MB, lista de dicts com todas as feições, hash, escrita em disco, commit) no event loop. "
             "No worker, `execute_import_commit` faz `db.refresh(job)` (1 SELECT) e `flush()` (1 INSERT) por entidade e relê o arquivo inteiro.",
        why="Arquivos grandes bloqueiam o loop por segundos e ocupam centenas de MiB; o commit tem ~2 round-trips por entidade.",
        impact="Latência global durante previews e importações demoradas (que ainda exigem lease — EST-07).",
        fix="Handler `def`/threadpool com streaming; limites de feições; verificar cancelamento a cada N entidades e usar `bulk_insert_mappings`.",
        validate="Arquivo GeoJSON de 20 MB local; medir tempo do loop (asyncio debug slow-callback) e RSS.",
        accept=["Teste: `/imports/preview` não bloqueia `/health/live` (latência < 100 ms durante o parse).",
                "Import de 50 mil pontos executa < 5 s de round-trips (contador de statements ≤ 2 por lote de 500)."],
        trigger="Arquivos > alguns MB (limite 20 MB); commit com dezenas de milhares de entidades.",
        growth="O(N) memória e O(2N) round-trips.",
        ev=[E("backend/app/api/v1/imports_exports.py", "async def preview_import("),
            E("backend/app/modules/imports/service.py", "if len(content) > 20 * 1024 * 1024:"),
            E("backend/app/modules/jobs/service.py", "db.refresh(job)", occ=1),
            E("backend/app/modules/jobs/service.py", "content = f.read()")],
        proof="verificado por leitura, não medido. Como medir: gerar GeoJSON de 20 MB e cronometrar o handler + `PYTHONASYNCIODEBUG=1`.",
        effort=2, gain=2, wave=2, rank=7),

    dict(
        id="PERF-06", sev="média", sub="A. Banco (índices)",
        title="Buscas por ILIKE '%q%' sem pg_trgm/GIN em sites, estruturas, cabos, dispositivos, clientes, usuários e notas de portas",
        cond="Busca global, listagens com `q` e relatórios (`Port.notes ILIKE '%danificad%'`); cresce com o tamanho das tabelas.",
        desc="Todas as consultas de texto usam `%termo%`, que não usa índices B-tree; as migrações não criam `pg_trgm` nem índices GIN. O termo também não escapa `%`/`_` (curinga).",
        why="Seq Scan por tabela e por requisição de busca (5 tabelas na busca global).",
        impact="Latência linear com o volume; combina-se com SEC-01 (busca anônima).",
        fix="`CREATE EXTENSION pg_trgm` + `GIN (code gin_trgm_ops)` (e name/serial/notes); escapar curingas do termo; para `q` curto exigir mínimo de 3 caracteres.",
        validate="`EXPLAIN (ANALYZE)` da busca em `structures`/`devices` com 100k+ linhas antes/depois.",
        accept=["Plano usa `Bitmap Index Scan on …trgm…` nas buscas (teste de plano; falha hoje)."],
        trigger="Medido 4,6 ms em 10.001 estruturas (Seq Scan, 10.001 linhas removidas); dor esperada em ordens de 10⁵ linhas (linear; não medido).",
        growth="O(N) por tabela por busca.",
        ev=[E("backend/app/modules/reports/service.py", "or_(Site.code.ilike(f\"%{clean_q}%\"), Site.name.ilike(f\"%{clean_q}%\")),"),
            E("backend/app/modules/inventory/service.py", "term = f\"%{q.strip()}%\"", occ=1),
            E("backend/app/modules/customers/service.py", "search = f\"%{q.strip()}%\""),
            E("backend/app/modules/reports/service.py", "Port.notes.ilike(\"%danificad%\"),", occ=1)],
        proof="medido (parcial): `EXPLAIN (ANALYZE)` em `tools/measure.py` — `Seq Scan on structures … Rows Removed by Filter: 10001`, 4,588 ms. Ausência de `pg_trgm`/GIN: `grep -rniE 'pg_trgm|gin' backend/migrations` → 0.",
        effort=1, gain=2, wave=2, rank=8),

    dict(
        id="PERF-07", sev="baixa", sub="A. Banco / B. Volume",
        title="Listagens paginadas com COUNT(*) + OFFSET + ORDER BY created_at sem índice de suporte",
        cond="Tabelas grandes (estruturas, cabos, medições, auditoria) e páginas profundas.",
        desc="As listagens fazem `count(*)` completo a cada página e `ORDER BY created_at DESC, id OFFSET n`; `created_at` não é indexado nas tabelas de inventário (só em auditoria/login). OFFSET profundo descarta linhas ordenadas.",
        why="Custo cresce com o tamanho da tabela e com a página (O(N log N) por página).",
        impact="Hoje baixo (medido 5,9 ms para OFFSET 9000 em 10 mil linhas); relevante em ordens de 10⁵–10⁶.",
        fix="Índice `(created_at DESC, id)`; paginação keyset; contagem aproximada/cache.",
        validate="`EXPLAIN (ANALYZE)` de `ORDER BY created_at DESC OFFSET 9000` antes/depois.",
        accept=["Plano usa `Index Scan Backward` na listagem (falha hoje)."],
        trigger="Não dói hoje (5,9 ms @10.001); gatilho esperado > 10⁵ linhas.",
        growth="O(N log N) por página (sort) e O(N) para COUNT.",
        ev=[E("backend/app/modules/inventory/service.py", "total = session.scalar(count_query) or 0", occ=1),
            E("backend/app/modules/inventory/service.py", "query.order_by(Site.created_at.desc(), Site.id).offset(offset).limit(page_size)"),
            E("backend/app/db/base.py", "created_at: Mapped[datetime] = mapped_column(")],
        proof="medido: `EXPLAIN (ANALYZE)` — `Sort … quicksort Memory: 2920kB` sobre Seq Scan (10.001 linhas), 5,924 ms; `count(structures.id)` 1,415 ms.",
        effort=1, gain=1, wave=4, rank=10),

    dict(
        id="PERF-08", sev="média", sub="B. Volume / F. Memória",
        title="Exportações carregam camadas inteiras em memória (`.all()`) e serializam JSON com indent",
        cond="`export_*` em redes grandes (após corrigir o worker — EST-01).",
        desc="`generate_*_export` faz `db.scalars(select(Site)).all()`, `select(Structure)`, `select(CableSegment)`, `select(Customer)` sem streaming e monta a lista completa de features antes de `json.dump(..., indent=2)`/`ET.tostring`.",
        why="Memória proporcional ao total de geometrias; sem paginação nem `yield_per`.",
        impact="Picos de memória no worker e tempo alto para redes com dezenas de milhares de segmentos.",
        fix="`yield_per`/cursor server-side e escrita incremental (NDJSON/`json.dump` por feature); limite por camada.",
        validate="Exportar dataset sintético (10k estruturas/5k segmentos) medindo RSS e tempo.",
        accept=["RSS do worker durante export ≤ 2× o tamanho do arquivo (teste com `tracemalloc`, falha hoje)."],
        trigger="Dezenas de milhares de segmentos/estruturas (não medido).",
        growth="O(N) memória.",
        ev=[E("backend/app/modules/exports/service.py", "sites = db.scalars(select(Site)).all()", occ=1),
            E("backend/app/modules/exports/service.py", "segments = db.scalars(select(CableSegment)).all()", occ=1),
            E("backend/app/modules/exports/service.py", "json.dump(geojson_data, f, ensure_ascii=False, indent=2)")],
        proof="verificado por leitura, não medido.", effort=2, gain=1, wave=3, rank=9),

    dict(
        id="PERF-09", sev="baixa", sub="D. Contenção de locks",
        title="Linha única network_topology_state atualizada em toda escrita de topologia serializa transações concorrentes",
        cond="Edição concorrente por vários usuários (fusão, divisão, importação, conexões).",
        desc="`bump_topology_revision` executa `UPDATE network_topology_state … WHERE id = 1` dentro de cada transação de topologia; o lock de linha só é liberado no `COMMIT`. É correto para o contador monotônico (**ponto forte**), mas serializa os commits.",
        why="Transações longas (importação, split) seguram o lock da linha e bloqueiam as demais escritas de topologia.",
        impact="Contenção sob edição concorrente intensa; hoje baixa.",
        fix="Manter o bump como último passo antes do commit (já é) e evitar transações longas; considerar sequence/advisory lock curto.",
        validate="`pg_locks`/`pg_stat_activity` durante 2 splits paralelos.",
        accept=["Duas divisões em segmentos distintos concluem sem esperar mais que o tempo de commit (teste de concorrência)."],
        trigger="Não medido; relevante com muitos editores simultâneos.",
        growth="Serialização O(1) por commit de topologia.",
        ev=[E("backend/app/modules/gis/service.py", "\"UPDATE network_topology_state \""),
            E("backend/app/modules/cables/service.py", "new_rev = bump_topology_revision(db)")],
        proof="verificado por leitura, não medido.", effort=2, gain=1, wave=4, rank=13),

    dict(
        id="PERF-10", sev="baixa", sub="A. Banco (N+1) / caminho de auth",
        title="Cada requisição autenticada faz 2 SELECTs (sessão e usuário por lazy load) e pode gravar last_activity_at",
        cond="Todas as rotas autenticadas.",
        desc="`get_active_session_by_token` faz `select(UserSession).join(User)` só para filtrar; `user_session.user` dispara um segundo SELECT (lazy). A cada 60 s de atividade há `UPDATE` + `COMMIT` dentro de um GET.",
        why="Custo fixo de ~2 round-trips por request (mais o commit periódico).",
        impact="Baixo; soma-se a todas as demais latências.",
        fix="`options(joinedload(UserSession.user))`/`contains_eager` e atualizar `last_activity_at` de forma assíncrona/amostrada.",
        validate="Contador de statements de `GET /auth/me`: 2 hoje → 1.",
        accept=["Teste: `GET /auth/me` executa 1 SELECT (falha hoje)."],
        trigger="Proporcional ao tráfego total.",
        growth="O(1) extra por request.",
        ev=[E("backend/app/modules/identity/service.py", ".join(User)"),
            E("backend/app/core/dependencies.py", "user = user_session.user"),
            E("backend/app/modules/identity/service.py", "user_session.last_activity_at = now")],
        proof="verificado por leitura, não medido.", effort=1, gain=1, wave=4, rank=11),

    dict(
        id="PERF-11", sev="baixa", sub="F. Crescimento sem limite",
        title="Sem retenção: login_attempts, user_sessions expiradas, audit_events e arquivos de exportação crescem indefinidamente",
        cond="Operação prolongada.",
        desc="A única rotina de limpeza (`clean_expired_previews_and_exports`) remove apenas `ImportPreview`; `login_attempts` (consultada a cada login com `OR`), sessões revogadas/expiradas e arquivos de exportação nunca são removidos.",
        why="Tabelas e disco crescem sem teto; o `count(*)` do rate limit varre um histórico crescente.",
        impact="Degradação lenta e consumo de disco.",
        fix="Job de retenção (ex.: 30 dias para `login_attempts`, 7 dias para sessões inválidas, TTL de exportações) e índice composto `(email, attempted_at)`.",
        validate="`SELECT count(*)` por tabela após semanas de operação; `EXPLAIN` do rate limit.",
        accept=["Teste: registros mais antigos que o TTL são removidos pelo worker (falha hoje)."],
        trigger="Meses de operação/alto volume de logins.",
        growth="O(t) linear no tempo.",
        ev=[E("backend/app/modules/jobs/service.py", "def clean_expired_previews_and_exports(db: Session) -> dict[str, int]:"),
            E("backend/app/modules/identity/models.py", "class LoginAttempt(Base):"),
            E("backend/app/modules/identity/models.py", "class UserSession(Base):")],
        proof="verificado por leitura, não medido.", effort=1, gain=1, wave=4, rank=12),

    dict(
        id="PERF-12", sev="média", sub="D. Conexões e concorrência",
        title="Um único processo uvicorn, pool de 10+20 conexões e nenhum statement_timeout/timeout de request",
        cond="Carga concorrente moderada ou 1 endpoint lento.",
        desc="`CMD uvicorn` sem `--workers`; handlers síncronos rodam na threadpool padrão (40 threads) sobre um pool de 30 conexões; `create_engine` não define `connect_args` (sem `statement_timeout`/`connect_timeout`) e não há timeout de requisição. "
             "Um endpoint lento retém conexões por segundos.",
        why="Poucas requisições lentas esgotam o pool (30) e as demais aguardam até `pool_timeout=30 s` — inclusive `/health/ready`, que também precisa de conexão.",
        impact="Falhas em cascata (readiness), latência global e impossibilidade de isolar endpoints caros.",
        fix="`--workers N` (ou réplicas), `statement_timeout` (ex.: 15 s) no `connect_args`, timeout de request no proxy, dimensionar pool por worker e separar rotas pesadas (fila).",
        validate="`tools/measure5.py` com timeout configurado; observar `/health/ready` sob carga.",
        accept=["Consulta com `pg_sleep(60)` é cancelada em ≤ statement_timeout (teste de integração, falha hoje).",
                "Readiness responde < 500 ms com 20 requisições caras concorrentes."],
        trigger="Medido: 20 requisições concorrentes ao dashboard → todas concluem ~17 s; readiness saltou para 1,1 s.",
        growth="Fila: latência ≈ N × tempo de serviço em 1 worker (GIL).",
        ev=[E("backend/app/db/session.py", "pool_size=settings.DB_POOL_SIZE,"),
            E("backend/app/core/config.py", "DB_MAX_OVERFLOW: int = 20"),
            E("backend/Dockerfile", "CMD [\"uvicorn\", \"app.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]")],
        proof="medido: `tools/measure5.py` — 20 GETs concorrentes: wall 16,9 s (sequencial teórico 21,9 s), p50 16,8 s; `/health/ready`: 151 ms (baseline) → [1126, 228, 259, 216, 260, 219] ms. In-process (TestClient), 1 processo: indica ordem de grandeza, não capacidade de produção.",
        effort=2, gain=2, wave=2, rank=4),

    dict(
        id="PERF-13", sev="baixa", sub="C. Caminho da requisição",
        title="/health/ready lê o diretório do Alembic do disco e usa uma conexão do pool a cada sonda (10 s)",
        cond="Sempre; agrava-se sob saturação do pool (PERF-12).",
        desc="`check_database_migrations` chama `ScriptDirectory.from_config(...)` (parse de arquivos de migração) a cada readiness; a rota depende de `get_db` (checkout no pool).",
        why="Custo desnecessário por sonda e acoplamento do readiness ao pool que ele deveria monitorar.",
        impact="Sondas lentas/falhas sob carga → container 'unhealthy'.",
        fix="Cachear o head esperado em memória no startup; usar conexão dedicada/curta (`engine.connect()` com timeout).",
        validate="Medir latência do readiness com e sem carga.",
        accept=["Readiness não faz I/O de arquivo por chamada (teste com mock de `ScriptDirectory`)."],
        trigger="Sondas a cada 10 s (compose); ruim sob pool esgotado.",
        growth="O(arquivos de migração) por sonda.",
        ev=[E("backend/app/db/health.py", "script_dir = ScriptDirectory.from_config(alembic_cfg)"),
            E("backend/app/api/v1/health.py", "def readiness(response: Response, db: Session = Depends(get_db)) -> dict[str, Any]:"),
            E("compose.yaml", "test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:8000/health/ready\"]")],
        proof="medido (parcial): readiness baseline 151 ms; ver PERF-12 para o comportamento sob carga.", effort=1, gain=1, wave=4, rank=14),

    dict(
        id="PERF-14", sev="média", sub="A. Banco (N+1) / B. Volume",
        title="Rastreio óptico: ≥ 5 queries por salto e cópia de listas por ramo; max_hops até 500 e max_results até 200 vindos do cliente",
        cond="`POST /topology/trace`, `/optical/budgets`, `/optical/simulations` (papel viewer) e o impacto (PERF-02).",
        desc="Cada iteração do BFS executa `db.get(Terminal)`, `db.scalars(FiberSegment)`, `db.scalars(Connection)`, `db.scalars(InternalEdge)`, splitters e checagem de endpoint; ramos copiam `current_steps + [next_step]` (O(H²) por caminho). "
             "O teto configurado `MAX_TRACE_HOPS=300` não é aplicado (EST-17).",
        why="Custo O(caminhos × saltos × queries) controlado pelo cliente dentro do teto de 200×500.",
        impact="Requisições de vários segundos com splitters em cascata (fan-out 1:8 × 1:8…).",
        fix="Pré-carregar o grafo do subconjunto (terminais/conexões/arestas) em 3–4 queries; aplicar `min(max_hops, MAX_TRACE_HOPS)`; memoizar; rate limit.",
        validate="`trace` a partir de terminal OLT com fan-out alto em dataset sintético; contar statements.",
        accept=["Statements do rastreio independem de `max_hops` (≤ 10 fixos) — falha hoje.",
                "`max_hops` efetivo ≤ `MAX_TRACE_HOPS`."],
        trigger="Topologias com splitters em cascata e milhares de ONUs por PON (não medido).",
        growth="O(P·H·q) queries; O(P·H²) memória de steps.",
        ev=[E("backend/app/modules/topology/service.py", "fiber_segs = db.scalars("),
            E("backend/app/modules/topology/service.py", "connections = db.scalars("),
            E("backend/app/modules/topology/service.py", "internal_edges = db.scalars("),
            E("backend/app/modules/topology/service.py", "new_steps = current_steps + [next_step]"),
            E("backend/app/schemas/topology.py", "le=500,")],
        proof="verificado por leitura, não medido (o dataset sintético do repositório tem só 5 conexões ativas, insuficiente para medir o rastreio em escala).",
        effort=3, gain=2, wave=3, rank=6),
]
