// GERADO por backend/scripts/export_permissions.py a partir de backend/app/core/permissions.py.
// NÃO edite à mão: rode `uv run python scripts/export_permissions.py` no backend.

export const PERMISSIONS = [
  "attachments:read",
  "attachments:write",
  "audit:read",
  "cables:read",
  "cables:write",
  "connectivity:read",
  "connectivity:write",
  "customers:read",
  "customers:write",
  "exports:read",
  "exports:write",
  "imports:read",
  "imports:write",
  "map:read",
  "measurements:read",
  "measurements:write",
  "network:read",
  "network:write",
  "optical:read",
  "optical:write",
  "reports:read",
  "settings:read",
  "settings:write",
  "splitters:read",
  "splitters:write",
  "topology:read",
  "topology:write",
  "users:read",
  "users:write",
] as const;

export const ROLE_PERMISSIONS = {
  admin: [
    "attachments:read",
    "attachments:write",
    "audit:read",
    "cables:read",
    "cables:write",
    "connectivity:read",
    "connectivity:write",
    "customers:read",
    "customers:write",
    "exports:read",
    "exports:write",
    "imports:read",
    "imports:write",
    "map:read",
    "measurements:read",
    "measurements:write",
    "network:read",
    "network:write",
    "optical:read",
    "optical:write",
    "reports:read",
    "settings:read",
    "settings:write",
    "splitters:read",
    "splitters:write",
    "topology:read",
    "topology:write",
    "users:read",
    "users:write",
  ],
  engineer: [
    "attachments:read",
    "attachments:write",
    "audit:read",
    "cables:read",
    "cables:write",
    "connectivity:read",
    "connectivity:write",
    "customers:read",
    "customers:write",
    "exports:read",
    "exports:write",
    "imports:read",
    "imports:write",
    "map:read",
    "measurements:read",
    "measurements:write",
    "network:read",
    "network:write",
    "optical:read",
    "optical:write",
    "reports:read",
    "splitters:read",
    "splitters:write",
    "topology:read",
    "topology:write",
  ],
  technician: [
    "attachments:read",
    "attachments:write",
    "audit:read",
    "map:read",
    "measurements:read",
    "measurements:write",
    "network:read",
    "optical:read",
    "reports:read",
  ],
  viewer: [
    "map:read",
    "network:read",
    "optical:read",
    "reports:read",
  ],
} as const;
